stages:
  - build

jar:
  stage: build
  when: manual
  image: eclipse-temurin:21-jdk-noble
  script:
    - ./scripts/task_linux.bash jar
  artifacts:
    paths:
      - build/libs/*
    expire_in: 1 hour

test:
  stage: build
  image: eclipse-temurin:21-jdk-noble
  script:
    - ./scripts/task_linux.bash test
  retry: 2
  artifacts:
    paths:
      - screen_capture.webm
    when: always
    expire_in: 1 hour

deb-amd64:
  stage: build
  image: eclipse-temurin:21-jdk-noble
  script:
    - ./scripts/task_linux.bash deb
  artifacts:
    paths:
      - build/jpackage/*
    expire_in: 1 hour

deb-arm64:
  stage: build
  tags:
    - saas-linux-small-arm64
  image: eclipse-temurin:21-jdk-noble
  script:
    - ./scripts/task_linux.bash deb
  artifacts:
    paths:
      - build/jpackage/*
    expire_in: 1 hour

rpm-amd64:
  stage: build
  image: eclipse-temurin:21-jdk-ubi9-minimal
  script:
    - ./scripts/task_linux.bash rpm
  artifacts:
    paths:
      - build/jpackage/*
    expire_in: 1 hour

exe-amd64:
  stage: build
  tags:
    - saas-windows-medium-amd64
  script:
    - powershell -File scripts/task_windows.ps1
  artifacts:
    paths:
      - build/jpackage/*
    expire_in: 1 hour
