package turbowin;

import java.awt.Cursor;
import java.util.List;
import javax.swing.SwingWorker;

public class mydevice_log extends javax.swing.JFrame {

  /** Creates new form mydevice_log */
  public mydevice_log() {
    initComponents();
    initComponents2();
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT
   * modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jScrollPane1 = new javax.swing.JScrollPane();
    jTextArea1 = new javax.swing.JTextArea();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setTitle("turboWin+ device log");

    jTextArea1.setEditable(false);
    jTextArea1.setColumns(20);
    jTextArea1.setRows(5);
    jScrollPane1.setViewportView(jTextArea1);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout
            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(
                layout
                    .createSequentialGroup()
                    .addContainerGap()
                    .addComponent(
                        jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 825, Short.MAX_VALUE)
                    .addContainerGap()));
    layout.setVerticalGroup(
        layout
            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(
                layout
                    .createSequentialGroup()
                    .addComponent(
                        jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 516, Short.MAX_VALUE)
                    .addContainerGap()));

    pack();
  } // </editor-fold>//GEN-END:initComponents

  String connected_devices_in_plain_language() {
    String connected_devices = null;

    if (main.RS232_connection_mode == 0) {
      connected_devices = "none";
    }
    if (main.RS232_connection_mode == 1) {
      connected_devices = "Vaisala PTB220 serial";
    }
    if (main.RS232_connection_mode == 2) {
      connected_devices = "Vaisala PTB330 serial";
    }
    if (main.RS232_connection_mode == 3) {
      connected_devices = "EUCAWS AWS serial";
    }
    if (main.RS232_connection_mode == 4) {
      connected_devices = "Mintaka DUO USB";
    }
    if (main.RS232_connection_mode == 5) {
      connected_devices = "Mintaka Star USB";
    }
    if (main.RS232_connection_mode == 6) {
      connected_devices = "Mintaka Star LAN";
    }
    if (main.RS232_connection_mode == 7) {
      connected_devices = "Mintaka Star serial + Mintaka StarX WiFi";
    }
    if (main.RS232_connection_mode == 8) {
      connected_devices = "Mintaka Star LAN + Mintaka StarX WiFi";
    }
    if (main.RS232_connection_mode == 9) {
      connected_devices = "OMC-140 AWS serial";
    }
    if (main.RS232_connection_mode == 10) {
      connected_devices = "OMC-140 AWS LAN";
    }
    if (main.RS232_connection_mode == 11) {
      connected_devices = "AMOS2X AWS serial";
    }

    if (main.RS232_connection_mode_II == 1) {
      if (connected_devices == null) {
        connected_devices = "Vaisala HMP155 USB";
      } else {
        connected_devices += " + Vaisala HMP155 USB";
      }
    }

    if (main.RS232_GPS_connection_mode == 1) {
      if (connected_devices == null) {
        connected_devices = "GPS (NMEA 0183)";
      } else {
        connected_devices += " + GPS (NMEA 0183)";
      }
    }

    return connected_devices;
  }

  void appendDeviceLogLine(String line, String newline) {
    jTextArea1.append(line);
    jTextArea1.append(newline);
  }

  void resetDeviceLogCursor() {
    setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
  }

  String log_separator() {
    String log_separator =
        "\n====================================================================================================================================\n";

    return log_separator;
  }

  private void initComponents2() {
    final String newline = System.getProperty("line.separator");

    // eg http://www.javacreed.com/swing-worker-example/

    setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
    setTitle("TurboWin+ device log");

    DeviceLogWorkflow.start(this, newline);

    //
    // GPS data (only available in this setting if it comes from a separated device, like a
    // mini-GPS)
    //
    if (main.RS232_GPS_connection_mode == 1) {
      setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));

      new SwingWorker<String, String>() {
        @Override
        protected String doInBackground() throws Exception {
          publish(new String[] {log_separator()});
          publish(new String[] {newline});
          publish(new String[] {"--- RECEIVED GPS DATA ---"});

          String GPS_memory_line = "";
          for (int m = main_RS232_RS422.MAX_GPS_ARRAY; m > 0; m--) {
            GPS_memory_line = main_RS232_RS422.GPS_array_device_log[m];
            publish(new String[] {GPS_memory_line});
          }

          return null;
        } // protected Void doInBackground() throws Exception

        @Override
        protected void process(List<String> data) {
          // process: Receives data chunks from the publish method asynchronously on the Event
          // Dispatch Thread.
          for (String received_line : data) {
            // NB eg http://www.javacreed.com/swing-worker-example/
            //    This swing component is only accessed from the process() method and never used
            // from within the doInBackbround() method
            //    or other methods directly (by directly we mean from the same thread) invoked from
            // it.

            // NB altijd in for loop omdat meerdere ontvangen string's verzameld kunnen zijn voordat
            // het hier geprocessed wordt(inherent aan SwingWorker)
            jTextArea1.append(received_line);
          }
        } // protected void process(List<String> data)

        @Override
        protected void done() {
          setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
        } // protected void done()
      }.execute(); // new SwingWorker<String, String>()
    } // if (main.RS232_GPS_connection_mode == 1)
  }

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info :
          javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(mydevice_log.class.getName())
          .log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(mydevice_log.class.getName())
          .log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(mydevice_log.class.getName())
          .log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(mydevice_log.class.getName())
          .log(java.util.logging.Level.SEVERE, null, ex);
    }
    // </editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(
        new Runnable() {
          @Override
          public void run() {
            new mydevice_log().setVisible(true);
          }
        });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTextArea jTextArea1;
  // End of variables declaration//GEN-END:variables
}
