package turbowin;

import java.awt.Cursor;
import java.awt.Font;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

public class mymaintenancedata extends javax.swing.JFrame {

  /** Creates new form mymaintenancedata */
  public mymaintenancedata() {
    initComponents();
    initComponents2();
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT
   * modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jScrollPane1 = new javax.swing.JScrollPane();
    jTextArea1 = new javax.swing.JTextArea();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setTitle("TurboWin+ maintenance data settings");

    jTextArea1.setEditable(false);
    jTextArea1.setColumns(20);
    jTextArea1.setRows(5);
    jScrollPane1.setViewportView(jTextArea1);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout
            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(
                layout
                    .createSequentialGroup()
                    .addContainerGap()
                    .addComponent(
                        jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 769, Short.MAX_VALUE)
                    .addContainerGap()));
    layout.setVerticalGroup(
        layout
            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(
                javax.swing.GroupLayout.Alignment.TRAILING,
                layout
                    .createSequentialGroup()
                    .addContainerGap()
                    .addComponent(
                        jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 489, Short.MAX_VALUE)
                    .addContainerGap()));

    pack();
  } // </editor-fold>//GEN-END:initComponents

  private void initComponents2() {
    if (main.mode.equals(main.MAINTENANCE_SHOW_DATA)) {
      show_data();
    } else if (main.mode.equals(main.MAINTENANCE_IMPORT_DATA)) {
      import_data();
    } else if (main.mode.equals(main.MAINTENANCE_EXPORT_DATA)) {
      export_data();
    }
  }

  void show_data() {
    MaintenanceDataShowWorkflow.start(this);
  }

  void prepareShowData() {
    Font font = new Font("Monospaced", Font.PLAIN, 13);
    jTextArea1.setFont(font);
    setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
  }

  void appendShowDataLine(String receivedLine, String newline) {
    jTextArea1.append(receivedLine);
    jTextArea1.append(newline);
  }

  void finishShowData() {
    setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
  }

  private void export_data() {
    boolean doorgaan = true;

    String export_dir =
        null; // NB Passing in a null string causes the file chooser to point to the user's default
    // directory (It is typically the "My Documents" folder on Windows)
    JFileChooser chooser = new JFileChooser(export_dir);
    chooser.setDialogTitle("Export maintenance data");
    chooser.setFileSelectionMode(
        JFileChooser
            .FILES_ONLY); // now the user can only select files (directories and files are still
    // visible)
    int result = chooser.showSaveDialog(mymaintenancedata.this);

    if (result == JFileChooser.APPROVE_OPTION) {
      maintenance_data_export_file =
          chooser
              .getSelectedFile()
              .getPath(); // getSelectedFile() -> in this case returns not a file but a directory !

      if (chooser.getSelectedFile().exists()) {
        int response =
            JOptionPane.showConfirmDialog(
                null,
                "Overwrite existing file?",
                main.APPLICATION_NAME + " confirm overwrite",
                JOptionPane.OK_CANCEL_OPTION,
                JOptionPane.QUESTION_MESSAGE);
        doorgaan = response != JOptionPane.CANCEL_OPTION;
      }

      if (doorgaan == true) {
        MaintenanceDataExportWorkflow.start(this, maintenance_data_export_file);
      } // if (doorgaan == true)
    } // if (result == JFileChooser.APPROVE_OPTION
    else // Cancel button
    {
      // mymaintenancedata.dispose(); // doesn't work
      // this.setVisible(false);      // doesn't work
      show_data();
    }
  }

  private void import_data() {
    // TODO add your handling code here:

    String input_dir =
        null; // NB Passing in a null string causes the file chooser to point to the user's default
    // directory (It is typically the "My Documents" folder on Windows)
    JFileChooser chooser = new JFileChooser(input_dir);
    chooser.setDialogTitle("Import maintenance data");

    int result = chooser.showOpenDialog(mymaintenancedata.this);
    if (result == JFileChooser.APPROVE_OPTION) {
      maintenance_data_import_file = chooser.getSelectedFile().getPath();

      MaintenanceDataImportWorkflow.start(this, maintenance_data_import_file);
    } // if (result == JFileChooser.APPROVE_OPTION
    else // Cancel button
    {
      show_data();
    }
  }

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info :
          javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException
        | InstantiationException
        | IllegalAccessException
        | javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(mymaintenancedata.class.getName())
          .log(java.util.logging.Level.SEVERE, null, ex);
    }
    // </editor-fold>

    // </editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(
        new Runnable() {
          @Override
          public void run() {
            new mymaintenancedata().setVisible(true);
          }
        });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTextArea jTextArea1;
  // End of variables declaration//GEN-END:variables

  private String maintenance_data_import_file =
      ""; // for importing maintenance data (configuration data) from import file
  private String maintenance_data_export_file =
      ""; // for exporting maintenance data (configuration data) to exportt file
}
