package turbowin;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.concurrent.ExecutionException;
import javax.swing.JOptionPane;
import javax.swing.SwingWorker;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellEditor;

public final class myobserver extends javax.swing.JFrame {

  /** Creates new form myobserver */
  public myobserver() {
    initComponents();
    initComponents2();
    setLocation(main.x_pos_frame, main.y_pos_frame);
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT
   * modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jSeparator1 = new javax.swing.JSeparator();
    jButton1 = new javax.swing.JButton();
    jButton2 = new javax.swing.JButton();
    jScrollPane1 = new javax.swing.JScrollPane();
    jTable1 = new javax.swing.JTable();
    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    jButton3 = new javax.swing.JButton();
    jLabel4 = new javax.swing.JLabel();
    jButton4 = new javax.swing.JButton();
    jButton5 = new javax.swing.JButton();
    jLabel5 = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setTitle("Observer");
    setMinimumSize(new java.awt.Dimension(800, 600));
    setResizable(false);

    jButton1.setText("OK");
    jButton1.addActionListener(
        new java.awt.event.ActionListener() {
          public void actionPerformed(java.awt.event.ActionEvent evt) {
            OK_button_actionPerformed(evt);
          }
        });

    jButton2.setText("Cancel");
    jButton2.addActionListener(
        new java.awt.event.ActionListener() {
          public void actionPerformed(java.awt.event.ActionEvent evt) {
            Cancel_button_actionPerformed(evt);
          }
        });

    jTable1.setModel(
        new javax.swing.table.DefaultTableModel(
            new Object[][] {
              {null, null, null, null},
              {null, null, null, null},
              {null, null, null, null},
              {null, null, null, null},
              {null, null, null, null},
              {null, null, null, null},
              {null, null, null, null},
              {null, null, null, null},
              {null, null, null, null},
              {null, null, null, null},
              {null, null, null, null},
              {null, null, null, null},
              {null, null, null, null},
              {null, null, null, null},
              {null, null, null, null},
              {null, null, null, null},
              {null, null, null, null},
              {null, null, null, null},
              {null, null, null, null},
              {null, null, null, null}
            },
            new String[] {"surname", "full initials*", "rank", "discharge book**"}) {
          Class[] types =
              new Class[] {
                java.lang.String.class,
                java.lang.String.class,
                java.lang.String.class,
                java.lang.String.class
              };

          public Class getColumnClass(int columnIndex) {
            return types[columnIndex];
          }
        });
    jTable1.setPreferredSize(new java.awt.Dimension(300, 322));
    jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
    jTable1.getTableHeader().setReorderingAllowed(false);
    jScrollPane1.setViewportView(jTable1);

    jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel1.setText(
        "*e.g. A.B.                                                   **discharge book or seaman's card number, if applicable");

    jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel2.setText("--- double click cell to insert new data ---");

    jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel3.setText("--- to clear records: double click surname cell and delete data ---");

    jButton3.setText("Internet");
    jButton3.addActionListener(
        new java.awt.event.ActionListener() {
          public void actionPerformed(java.awt.event.ActionEvent evt) {
            Internet_button_actionPerformed(evt);
          }
        });

    jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel4.setText("--- single click row to select observer ---");
    jLabel4.setMaximumSize(new java.awt.Dimension(338, 14));
    jLabel4.setMinimumSize(new java.awt.Dimension(338, 14));

    jButton4.setText("Back");
    jButton4.addActionListener(
        new java.awt.event.ActionListener() {
          public void actionPerformed(java.awt.event.ActionEvent evt) {
            Back_button_actionPerformed(evt);
          }
        });

    jButton5.setText("Stop");
    jButton5.addActionListener(
        new java.awt.event.ActionListener() {
          public void actionPerformed(java.awt.event.ActionEvent evt) {
            Stop_button_actionParformed(evt);
          }
        });

    jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel5.setText("-");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout
            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(
                layout
                    .createSequentialGroup()
                    .addGroup(
                        layout
                            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(
                                layout
                                    .createSequentialGroup()
                                    .addGroup(
                                        layout
                                            .createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(
                                                layout
                                                    .createSequentialGroup()
                                                    .addGap(44, 44, 44)
                                                    .addGroup(
                                                        layout
                                                            .createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment
                                                                    .LEADING,
                                                                false)
                                                            .addComponent(
                                                                jScrollPane1,
                                                                javax.swing.GroupLayout.Alignment
                                                                    .TRAILING,
                                                                javax.swing.GroupLayout
                                                                    .DEFAULT_SIZE,
                                                                713,
                                                                Short.MAX_VALUE)
                                                            .addComponent(
                                                                jLabel1,
                                                                javax.swing.GroupLayout
                                                                    .DEFAULT_SIZE,
                                                                javax.swing.GroupLayout
                                                                    .DEFAULT_SIZE,
                                                                Short.MAX_VALUE)
                                                            .addComponent(
                                                                jLabel3,
                                                                javax.swing.GroupLayout
                                                                    .DEFAULT_SIZE,
                                                                javax.swing.GroupLayout
                                                                    .DEFAULT_SIZE,
                                                                Short.MAX_VALUE)
                                                            .addComponent(
                                                                jLabel2,
                                                                javax.swing.GroupLayout
                                                                    .DEFAULT_SIZE,
                                                                javax.swing.GroupLayout
                                                                    .DEFAULT_SIZE,
                                                                Short.MAX_VALUE)
                                                            .addComponent(
                                                                jLabel4,
                                                                javax.swing.GroupLayout.Alignment
                                                                    .TRAILING,
                                                                javax.swing.GroupLayout
                                                                    .DEFAULT_SIZE,
                                                                javax.swing.GroupLayout
                                                                    .DEFAULT_SIZE,
                                                                Short.MAX_VALUE)
                                                            .addComponent(
                                                                jLabel5,
                                                                javax.swing.GroupLayout
                                                                    .DEFAULT_SIZE,
                                                                javax.swing.GroupLayout
                                                                    .DEFAULT_SIZE,
                                                                Short.MAX_VALUE)))
                                            .addGroup(
                                                layout
                                                    .createSequentialGroup()
                                                    .addGap(160, 160, 160)
                                                    .addComponent(
                                                        jButton4,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        80,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(
                                                        jButton1,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        80,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(
                                                        jButton2,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        80,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(
                                                        jButton3,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        80,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(
                                                        jButton5,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        80,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(0, 36, Short.MAX_VALUE))
                            .addGroup(
                                layout
                                    .createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jSeparator1)))
                    .addContainerGap()));
    layout.setVerticalGroup(
        layout
            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(
                javax.swing.GroupLayout.Alignment.TRAILING,
                layout
                    .createSequentialGroup()
                    .addGap(39, 39, 39)
                    .addComponent(
                        jScrollPane1,
                        javax.swing.GroupLayout.PREFERRED_SIZE,
                        343,
                        javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel1)
                    .addPreferredGap(
                        javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                    .addComponent(
                        jLabel4,
                        javax.swing.GroupLayout.PREFERRED_SIZE,
                        14,
                        javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel2)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel3)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel5)
                    .addGap(4, 4, 4)
                    .addComponent(
                        jSeparator1,
                        javax.swing.GroupLayout.PREFERRED_SIZE,
                        2,
                        javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(15, 15, 15)
                    .addGroup(
                        layout
                            .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(
                                jButton3,
                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                25,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(
                                jButton2,
                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                25,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(
                                jButton1,
                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                25,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(
                                jButton4,
                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                25,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(
                                jButton5,
                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                25,
                                javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(15, 15, 15)));

    pack();
  } // </editor-fold>//GEN-END:initComponents

  /***********************************************************************************************/
  /*                                                                                             */
  /*                                                                                             */
  /*                                                                                             */
  /***********************************************************************************************/
  private void initComponents2() {

    if (main.offline_mode == true) {
      jButton3.setText("Help");
    }

    // hide Back/Stop buttons if not in next_screen_mode
    if (main.in_next_sequence == false) {
      jButton4.setEnabled(false); // back button
      jButton5.setEnabled(false); // stop button
    }

    /* for Germany recruited ships different column heading (christian name instead of full initials) */

    // http://forums.sun.com/thread.jspa?threadID=751059
    //
    // Creating methods getColumnNames() and setColumnNames() does nothing since the
    // getColumnNames() method of the TableModel is not invoked again after the TableModel has been
    // added to the table
    // You could recreate the entire TableColumnModel (and TableColumns) by doing something like:
    //
    // DefaultTableModel model = new DefaultTableModel(....);
    // table.setModel( model );

    if (main.recruiting_country.indexOf("GERMANY") != -1) {
      DefaultTableModel model =
          new DefaultTableModel(
              new Object[][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
              },
              new String[] {"surname", "full christian name*", "rank", "discharge book**"});

      jTable1.setModel(model);

      jLabel1.setText(
          "*e.g. Heinz Andreas Dieter                                        **discharge book or seaman's card number if applicable");
    } // if (main.recruiting_country.indexOf("GERMANY") != -1)

    if (main.eucaws_obs_id == true) {
      DefaultTableModel model =
          new DefaultTableModel(
              new Object[][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
              },
              new String[] {"surname", "full initials*", "OBS_ID**", "discharge book***"}) {
            @Override
            public boolean isCellEditable(int row, int column) {
              return column != 2; // Column index 2 (OBS_ID**) is uneditable
            }
          };

      jTable1.setModel(model);

      jLabel1.setText(
          "*e.g. A.B.          **computed          ***discharge book or seaman's card number if applicable");

      jLabel2.setText("--- double click cell to insert new data (OBS_ID excepted) ---");

      jLabel5.setText("--- uploading observers data: 'Maintenance -> Move log files' ---");
    } // if (main.eucaws_obs_id == true)

    lees_observer_log_en_vul_table();
  }

  /***********************************************************************************************/
  /*                                                                                             */
  /*                                                                                             */
  /*                                                                                             */
  /***********************************************************************************************/
  public void stopCellEditing() {
    TableCellEditor editor = jTable1.getCellEditor();
    if (editor != null) {
      editor.stopCellEditing();
    }
  }

  /***********************************************************************************************/
  /*                                                                                             */
  /*                                                                                             */
  /*                                                                                             */
  /***********************************************************************************************/
  private void OK_button_actionPerformed(
      java.awt.event.ActionEvent evt) { // GEN-FIRST:event_OK_button_actionPerformed
    // TODO add your handling code here:

    if (main.eucaws_obs_id == true) {
      /* initialisation */
      clear_observer_data_array();
      boolean checks_ok = true;

      // NOTE: stopCellEditing() is called automatically when you hit [Enter] or [Tab] on a cell
      // indicating the end of editing
      //       But we want it to stop if the user click the OK button, if fuction stopCellEditing()
      // is not called
      //       it is possible that the last changes/inserts of a cell, if this cell has still the
      // focus, are ignored
      //       when pressing the OK button
      stopCellEditing();

      // collect data from all table cells
      for (int r = 0; r < OBSERVER_ROWS; r++) {
        for (int c = 0; c < OBSERVER_COLUMNS; c++) {
          observer_data[r][c] = (String) jTable1.getValueAt(r, c);
        }
      }

      // check the inserted values
      checks_ok = check_data_observer_log();

      // compute OBS_Ids
      if (checks_ok) {
        checks_ok = compute_OBS_IDs();
      }

      if (checks_ok) {
        /* save observer data to file */
        schrijf_observer_log();

        // retrieve selected observer (surname + full initials + rank + discharge number)
        int selectedRow =
            jTable1.getSelectedRow(); // index of the firstselected row (start 0); -1 if no row was
        // selected
        // JOptionPane.showMessageDialog(null, selectedRow);
        if (selectedRow != -1) // -1 means no observer row selected
        {
          // nu kan het zijn dat na invullen van een nieuwe naam deze direct wordt geselecteerd
          // dan was deze bv Janssen;K;;; en wordt zo geschreven in immt.log
          // maar wordt opgeslagen in observer.log als Janssen;K;-;-;
          // dan bij downloaden log files geen match !!

          if (observer_data[selectedRow][1].equals("") == true) // full initials
          {
            observer_data[selectedRow][1] = "-";
          }
          if (observer_data[selectedRow][2].equals("") == true) // rank (or OBS_ID)
          {
            observer_data[selectedRow][2] = "-";
          }
          if (observer_data[selectedRow][3].equals("") == true) // discharge book number
          {
            observer_data[selectedRow][3] = "-";
          }

          selected_observer =
              observer_data[selectedRow][0]
                  + ";"
                  + observer_data[selectedRow][1]
                  + ";"
                  + observer_data[selectedRow][2]
                  + ";"
                  + observer_data[selectedRow][3]
                  + ";";
        } // if (selectedRow != -1)

        /* update observer field on main (progress) screen */
        main.observer_field_update();

        /* close input page */
        setVisible(false);
        dispose();
      } // if (checks_ok)

      /* next screen if in_next_screen mode */
      if (main.in_next_sequence == true) {
        // last input screen of the next_screen_mode sequence
        main.in_next_sequence = false;
      }

    } // if (main.eucaws_obs_id == true)
    else // NOT obs_id
    {
      /* initialisation */
      clear_observer_data_array();

      // NOTE: stopCellEditing() is called automatically when you hit [Enter] or [Tab] on a cell
      // indicating the end of editing
      //       But we want it to stop if the user click the OK button, if fuction stopCellEditing()
      // is not called
      //       it is possible that the last changes/inserts of a cell, if this cell has still the
      // focus, are ignored
      //       when pressing the OK button
      stopCellEditing();

      // collect data from all table cells
      for (int r = 0; r < OBSERVER_ROWS; r++) {
        for (int c = 0; c < OBSERVER_COLUMNS; c++) {
          observer_data[r][c] = (String) jTable1.getValueAt(r, c);
        }
      }

      /* save observer data to file */
      schrijf_observer_log();

      // retrieve selected observer (surname + full initials + rank + discharge number)
      int selectedRow =
          jTable1.getSelectedRow(); // index of the firstselected row (start 0); -1 if no row was
      // selected
      // JOptionPane.showMessageDialog(null, selectedRow);
      if (selectedRow != -1) // -1 means no observer row selected
      {
        // nu kan het zijn dat na invullen van een nieuwe naam deze direct wordt geselecteerd
        // dan was deze bv Janssen;K;;; en wordt zo geschreven in immt.log
        // maar wordt opgeslagen in observer.log als Janssen;K;-;-;
        // dan bij downloaden log files geen match !!

        if (observer_data[selectedRow][1].equals("") == true) // full initials
        {
          observer_data[selectedRow][1] = "-";
        }
        if (observer_data[selectedRow][2].equals("") == true) // rank
        {
          observer_data[selectedRow][2] = "-";
        }
        if (observer_data[selectedRow][3].equals("") == true) // discharge book number
        {
          observer_data[selectedRow][3] = "-";
        }

        selected_observer =
            observer_data[selectedRow][0]
                + ";"
                + observer_data[selectedRow][1]
                + ";"
                + observer_data[selectedRow][2]
                + ";"
                + observer_data[selectedRow][3]
                + ";";
      } // if (selectedRow != -1)

      /* update observer field on main (progress) screen */
      main.observer_field_update();

      /* close input page */
      setVisible(false);
      dispose();

      /* next screen if in_next_screen mode */
      if (main.in_next_sequence == true) {
        // last input screen of the next_screen_mode sequence
        main.in_next_sequence = false;
      }
    } // else (NOT obs_id)
  } // GEN-LAST:event_OK_button_actionPerformed

  /***********************************************************************************************/
  /*                                                                                             */
  /*                                                                                             */
  /*                                                                                             */
  /***********************************************************************************************/
  private boolean compute_OBS_IDs() {
    boolean checks_ok = true;

    for (int r = 0; r < OBSERVER_ROWS; r++) {
      String surname = observer_data[r][0];
      String initials =
          observer_data[r][
              1]; // e.g. 'J' or "J.B. or 'JB' or 'JBC' or 'J.B.C.' or 'Hans Christansen'
      String obs_id = observer_data[r][2]; // colomn 2 (0 = first column) = OBS_ID

      // String row_number = String.valueOf(r + 1);
      // String info3 = "TEST (" + "row " + row_number + ")" + "\n" + "obs_id=" + obs_id;
      // JOptionPane.showMessageDialog(null, info3, main.APPLICATION_NAME + " error",
      // JOptionPane.WARNING_MESSAGE);

      if ("".equals(obs_id) && (!"".equals(surname))) // OBS_ID is empty and surname is inserted!
      {
        // check the initials
        StringBuilder obs_id_raw =
            new StringBuilder(); // obs_id_raw: after first computation but still not checked for
        // 'doubles'

        // Collect up to 2 valid letters
        // where a valid character is defined as a letter (e.g., A–Z, a–z) — so digits (0–9),
        // punctuation (like .), and other symbols are ignored.
        for (int i = 0; i < initials.length() && obs_id_raw.length() < 2; i++) {
          char c = initials.charAt(i);
          if (Character.isLetter(c)) {
            obs_id_raw.append(Character.toUpperCase(c)); // always append the letter as upper case
          }
        }
        // so now":
        // -empty            -> ""
        // J                 -> J
        // J.B.              -> JB
        // J.B.C.            -> JB
        // Hans Christiansen -> HA
        //

        // Pad with '1' characters if less than 3
        while (obs_id_raw.length() < 3) {
          obs_id_raw.append('1');
        }
        // so now":
        // ""                -> 111
        // J                 -> J11
        // JB                -> JB1
        // JB                -> JB1
        // HA                -> HA1
        //

        boolean duplicate = false;
        for (int x = 0; x < OBSERVER_ROWS; x++) // do not use r as iterator!
        {
          // duplicate
          // String r_num = String.valueOf(r);
          // String x_num = String.valueOf(x);
          //
          // String info7 = "compute_OBS_IDs(): " + "r_num=" + r_num + " x_num=" + x_num;
          // JOptionPane.showMessageDialog(null, info7, main.APPLICATION_NAME + " error",
          // JOptionPane.WARNING_MESSAGE);

          // if (r != x)
          // {
          String existing_obs_id = observer_data[x][2]; // column 3 = index 2 = OBS_ID

          if ((!obs_id_raw.toString().equals("111"))
              && (existing_obs_id.equals(obs_id_raw.toString()))) {
            // duplicate
            // String r_num2 = String.valueOf(r);
            // String x_num2 = String.valueOf(x);
            // String info2 = "compute_OBS_IDs() duplicate found: " + "r_num=" + r_num2 + " x_num="
            // + x_num2 + "\n" + "existing_obs_id=" + existing_obs_id + " ;obs_id_raw=" +
            // obs_id_raw;
            // JOptionPane.showMessageDialog(null, info2, main.APPLICATION_NAME + " error",
            // JOptionPane.WARNING_MESSAGE);

            duplicate = true; // Duplicate found
            break;
          }
          // } // if (r != x)
        } // for (int x = 0; x < OBSERVER_ROWS; x++)

        if (!duplicate) {
          observer_data[r][2] = obs_id_raw.toString();
        }

        if (duplicate) {
          String obs_id_raw_alternative = compute_alternative_OBS_ID(obs_id_raw);

          if (!"".equals(obs_id_raw_alternative)) {
            observer_data[r][2] = obs_id_raw_alternative;
          } else {
            checks_ok = false;
            String info =
                "Error when computing OBS_ID (more than 9 records with the same first 2 letters of 'full initials'?), observer data will not be saved";
            JOptionPane.showMessageDialog(
                null, info, main.APPLICATION_NAME + " error", JOptionPane.WARNING_MESSAGE);
          }
        }
      } // for (int r = 0; r < OBSERVER_ROWS; r++)
    } // if ("".equals(obs_id))

    return checks_ok;
  }

  /***********************************************************************************************/
  /*                                                                                             */
  /*                                                                                             */
  /*                                                                                             */
  /***********************************************************************************************/
  private String compute_alternative_OBS_ID(StringBuilder obs_id_raw) {
    String obs_id_raw_alternative = "";
    int MAX_DIGIT = 9;

    for (int y = 0; y < MAX_DIGIT; y++) {
      if (obs_id_raw.length() != 3) {
        // throw new IllegalArgumentException("obs_id_raw must be exactly 3 characters long.");
        obs_id_raw_alternative = "";
        break;
      }

      char lastChar = obs_id_raw.charAt(2);

      if (!Character.isDigit(lastChar)) {
        // throw new IllegalArgumentException("Last character must be a digit.");
        obs_id_raw_alternative = "";
        break;
      }

      int digit = lastChar - '0'; // Convert char to int
      digit++; // Increment

      if (digit > 9) {
        // throw new IllegalArgumentException("Digit overflow: only 1 to 9 supported.");
        obs_id_raw_alternative = "";
        break;
      }

      obs_id_raw.setCharAt(2, (char) ('0' + digit)); // Convert back to char and set

      // String row_num = String.valueOf(y);
      // String info2 = "compute_alternative_OBS_ID; increasing for duplicate (" + "y " + row_num +
      // ")" + "\n" + "obs_id_raw=" + obs_id_raw;
      // JOptionPane.showMessageDialog(null, info2, main.APPLICATION_NAME + " error",
      // JOptionPane.WARNING_MESSAGE);

      boolean duplicate = false;
      for (int x = 0; x < OBSERVER_ROWS; x++) // do not use r as iterator!
      {
        String existing_obs_id = observer_data[x][2]; // column 3 = index 2 = OBS_ID
        if ((!obs_id_raw.toString().equals("111"))
            && (existing_obs_id.equals(obs_id_raw.toString()))) {
          duplicate = true; // Duplicate found
          break;
        }
      } // for (int x = 0; x < OBSERVER_ROWS; x++)

      if (!duplicate) {
        obs_id_raw_alternative = obs_id_raw.toString();
        break;
      }
    } // for (int y = 0; y < MAX_DIGIT; y++)

    return obs_id_raw_alternative; // NB obs_id_raw_alternative = "" if error or duplicate check
    // coulnot be performed becuse > 9 options
  }

  /***********************************************************************************************/
  /*                                                                                             */
  /*                                                                                             */
  /*                                                                                             */
  /***********************************************************************************************/
  private boolean check_data_observer_log() {
    // check 'full initials' [1], must be present (if surname is not present the record will be
    // never saved (same result as the complete record is deleted)
    if (main.eucaws_obs_id == true) {
      if (observer_data == null) {
        return true;
      } else {
        for (int r = 0; r < OBSERVER_ROWS; r++) {
          /*
                         if (("".equals(observer_data[r][0])) && (!"".equals(observer_data[r][1])))
                         {
                            // name empty but initials not empty
                            String row_num = String.valueOf(r + 1);
                            String info = "surname empty (" + "row " + row_num + ")" + "\n" + "observer data changes will not be saved";
                            JOptionPane.showMessageDialog(null, info, main.APPLICATION_NAME + " error", JOptionPane.WARNING_MESSAGE);
                            return false;
                         }
          */
          if ((!"".equals(observer_data[r][0])) && ("".equals(observer_data[r][1]))) {
            // name not empty but initials empty
            String row_num = String.valueOf(r + 1);
            String info =
                "full initials empty ("
                    + "row "
                    + row_num
                    + ")"
                    + "\n"
                    + "observer data changes will not be saved";
            JOptionPane.showMessageDialog(
                null, info, main.APPLICATION_NAME + " error", JOptionPane.WARNING_MESSAGE);
            return false;
          }
        } // for (int r = 0; r < OBSERVER_ROWS; r++)
      } // else
    } // if (main.eucaws_obs_id == true)

    return true;
  }

  /***********************************************************************************************/
  /*                                                                                             */
  /*                                                                                             */
  /*                                                                                             */
  /***********************************************************************************************/
  private void clear_observer_data_array() {
    for (int r = 0; r < OBSERVER_ROWS; r++) {
      for (int c = 0; c < OBSERVER_COLUMNS; c++) {
        observer_data[r][c] = "";
      }
    }
  }

  /***********************************************************************************************/
  /*                                                                                             */
  /*                                                                                             */
  /*                                                                                             */
  /***********************************************************************************************/
  private void lees_observer_log_en_vul_table() {
    /* NB input/output GUI always via a SwingWorker (Core Java Volume 1 bld 795 e.v.; Volume 2 bld 37, 215) */

    new SwingWorker<Void, Void>() {
      @Override
      protected Void doInBackground() throws Exception {
        String record;
        int pos_begin;
        int pos_eind;
        int r;

        /* initialisation */
        clear_observer_data_array();

        String volledig_path = main.logs_dir + java.io.File.separator + main.OBSERVER_LOG;

        /* read all lines from observer log */
        try (BufferedReader in = new BufferedReader(new FileReader(volledig_path))) {
          r = 0;
          while ((record = in.readLine()) != null) {
            pos_begin = 0;
            pos_eind = 0;
            for (int c = 0; c < OBSERVER_COLUMNS; c++) {
              pos_eind =
                  record.indexOf(
                      ";",
                      pos_begin); // Returns the index within this string of the first occurrence of
              // the specified substring, starting at the specified index.

              if (pos_eind != -1) {
                observer_data[r][c] = record.substring(pos_begin, pos_eind);
                pos_begin = pos_eind + 1;
              } else {
                break;
              }
            } // for (int c = 0; c < OBSERVER_COLUMNS; c++)

            r++;

            /* safety */
            if (r >= OBSERVER_ROWS) {
              break;
            }
          } // while((file_line = in.readLine()) != null)
        } // try
        catch (IOException ex) {
          // do nothing, possible file was never created
        } // catch

        return null;
      } // protected Void doInBackground() throws Exception

      @Override
      protected void done() {
        // collect data from all table cells
        for (int r = 0; r < OBSERVER_ROWS; r++) {
          for (int c = 0; c < OBSERVER_COLUMNS; c++) {
            jTable1.setValueAt(observer_data[r][c], r, c);
          }
        } // for (int r = 0; r < OBSERVER_ROWS; r++)

        // select the row of the observer which was selected befor
        //
        for (int r = 0; r < OBSERVER_ROWS; r++) {
          if ((selected_observer.compareTo("") != 0)
              && (observer_data[r][0].compareTo("") != 0)
              && (observer_data[r][1].compareTo("") != 0)) {
            if ((selected_observer.indexOf(observer_data[r][0]) != -1)
                && // [0] : surname
                (selected_observer.indexOf(observer_data[r][1]) != -1)) // [1] : initials
            {
              jTable1.setRowSelectionInterval(r, r);
              break;
            }
          }
        } // for (int r = 0; r < OBSERVER_ROWS; r++)
      } // protected void done()
    }.execute(); // new SwingWorker<Void, Void>()
  }

  /***********************************************************************************************/
  /*                                                                                             */
  /*                                                                                             */
  /*                                                                                             */
  /***********************************************************************************************/
  private void schrijf_observer_log() {
    /* NB input/output in a GUI always via a SwingWorker (Core Java Volume 1 bld 795 e.v.; Volume 2 bld 37, 215) */
    boolean doorgaan = true;

    // first test if logs folder was defined
    if (main.logs_dir.equals("") == true) {
      JOptionPane.showMessageDialog(
          null,
          "Logs folder unknown, please select: Maintenance -> Log files settings",
          main.APPLICATION_NAME + " error",
          JOptionPane.WARNING_MESSAGE);
      doorgaan = false;
    }

    // ok logs dir is known
    if (doorgaan == true) {
      new SwingWorker<String, Void>() {
        @Override
        protected String doInBackground() throws Exception {
          String observer_log_ok = "OK";
          String volledig_path = main.logs_dir + java.io.File.separator + main.OBSERVER_LOG;

          try (BufferedWriter out = new BufferedWriter(new FileWriter(volledig_path))) {
            for (int r = 0; r < OBSERVER_ROWS; r++) {
              // at least surname must be present (c = 0)
              if ((observer_data[r][0] != null) && (observer_data[r][0].compareTo("") != 0)) {
                for (int c = 0; c < OBSERVER_COLUMNS; c++) {
                  if ((observer_data[r][c] != null) && (observer_data[r][c].compareTo("") != 0)) {
                    out.write(observer_data[r][c]);
                  } else // empty field/cell
                  {
                    out.write("-");
                  }

                  out.write(";"); // semi-column seperated
                } // for (int c = 0; c < OBSERVER_COLUMNS; c++)

                out.newLine(); // newLine(): write a line separator. The line separator string is
                // defined by the system property line.separator, and is not
                // necessarily a single newline ('\n') character.
              } // if ((observer_data[r][0] != null)
            } // for (int r = 0; r < OBSERVER_ROWS; r++)

          } // try
          catch (IOException ex) {
            // JOptionPane.showMessageDialog(null, "unable to write to: " + volledig_path,
            // main.APPLICATION_NAME + " error", JOptionPane.WARNING_MESSAGE);
            observer_log_ok = "unable to write to: " + volledig_path;
          } // catch

          return observer_log_ok;
        } // protected Void doInBackground() throws Exception

        @Override
        protected void done() {
          try {
            String result_observer_log_ok = get();
            if (result_observer_log_ok.equals("OK") == false) {
              JOptionPane.showMessageDialog(
                  null,
                  result_observer_log_ok,
                  main.APPLICATION_NAME + " error",
                  JOptionPane.WARNING_MESSAGE);
            }
          } // protected void done()
          catch (InterruptedException | ExecutionException ex) {
            System.out.println("--- Function schrijf_observer_log(): " + ex);
          }
        } // protected void done()
      }.execute(); // new SwingWorker<Void, Void>()
    } // if (doorgaan == true)
  }

  /***********************************************************************************************/
  /*                                                                                             */
  /*                                                                                             */
  /*                                                                                             */
  /***********************************************************************************************/
  private void Cancel_button_actionPerformed(
      java.awt.event.ActionEvent evt) { // GEN-FIRST:event_Cancel_button_actionPerformed
    // TODO add your handling code here:

    /* close input page */
    setVisible(false);
    dispose();

    /* next screen in in next sequence mode */
    if (main.in_next_sequence == true) {
      // last input screen of the next_screen_mode sequence
      main.in_next_sequence = false;
    }
  } // GEN-LAST:event_Cancel_button_actionPerformed

  /***********************************************************************************************/
  /*                                                                                             */
  /*                                                                                             */
  /*                                                                                             */
  /***********************************************************************************************/
  private void Internet_button_actionPerformed(
      java.awt.event.ActionEvent evt) { // GEN-FIRST:event_Internet_button_actionPerformed
    // TODO add your handling code here:
    main.help_mouseClicked(OBSERVER_HELP_DIR);
  } // GEN-LAST:event_Internet_button_actionPerformed

  /***********************************************************************************************/
  /*                                                                                             */
  /*                                                                                             */
  /*                                                                                             */
  /***********************************************************************************************/
  private void Back_button_actionPerformed(
      java.awt.event.ActionEvent evt) { // GEN-FIRST:event_Back_button_actionPerformed
    // TODO add your handling code here:
    setVisible(false);
    dispose();

    previous_screen();
  } // GEN-LAST:event_Back_button_actionPerformed

  /***********************************************************************************************/
  /*                                                                                             */
  /*                                                                                             */
  /*                                                                                             */
  /***********************************************************************************************/
  private void Stop_button_actionParformed(
      java.awt.event.ActionEvent evt) { // GEN-FIRST:event_Stop_button_actionParformed
    // TODO add your handling code here:
    setVisible(false);
    dispose();

    main.in_next_sequence = false;
  } // GEN-LAST:event_Stop_button_actionParformed

  /***********************************************************************************************/
  /*                                                                                             */
  /*                                                                                             */
  /*                                                                                             */
  /***********************************************************************************************/
  private void previous_screen() {
    // if (main.GUI_mode.equals(main.GUI_LIGHT))
    // {
    //   mywind form = new mywind();
    //   form.setSize(800, 600);
    //   form.setVisible(true);
    // }
    // else
    // {
    mycloudcover form = new mycloudcover();
    form.setSize(800, 600);
    form.setVisible(true);
    // }
  }

  /***********************************************************************************************/
  /*                                                                                             */
  /*                                                                                             */
  /*                                                                                             */
  /***********************************************************************************************/
  // private void next_screen()
  // {
  //   myposition form = new myposition();
  //   form.setSize(800, 600);
  //   form.setVisible(true);
  // }

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    java.awt.EventQueue.invokeLater(
        new Runnable() {
          @Override
          public void run() {
            new myobserver().setVisible(true);
          }
        });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButton1;
  private javax.swing.JButton jButton2;
  private javax.swing.JButton jButton3;
  private javax.swing.JButton jButton4;
  private javax.swing.JButton jButton5;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JSeparator jSeparator1;
  private javax.swing.JTable jTable1;
  // End of variables declaration//GEN-END:variables

  // constants
  public static final int OBSERVER_ROWS =
      20; // static!!    // zie ook MAX_AANTAL_WAARNEMERS in main.java
  public static final int OBSERVER_COLUMNS = 4; // static!!
  private final String OBSERVER_HELP_DIR = "observer.pdf";

  // scope this module + myturbowin.java main module (all of type: static)
  public static String[][] observer_data =
      new String[OBSERVER_ROWS][OBSERVER_COLUMNS]; // default values: null
  public static String selected_observer = "";
}
