package turbowin;

import javax.swing.JOptionPane;

public final class myobsformat extends javax.swing.JFrame {

  /** Creates new form myobsformat */
  public myobsformat() {
    initComponents();
    initComponents2();
    setLocation(main.x_pos_frame, main.y_pos_frame);
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT
   * modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    buttonGroup1 = new javax.swing.ButtonGroup();
    buttonGroup3 = new javax.swing.ButtonGroup();
    jSeparator1 = new javax.swing.JSeparator();
    jButton1 = new javax.swing.JButton();
    jButton2 = new javax.swing.JButton();
    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    jPanel4 = new javax.swing.JPanel();
    jRadioButton1 = new javax.swing.JRadioButton();
    jRadioButton2 = new javax.swing.JRadioButton();
    jRadioButton7 = new javax.swing.JRadioButton();
    jPanel1 = new javax.swing.JPanel();
    jRadioButton3 = new javax.swing.JRadioButton();
    jRadioButton4 = new javax.swing.JRadioButton();
    jLabel3 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    jPanel2 = new javax.swing.JPanel();
    jCheckBox1 = new javax.swing.JCheckBox();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setTitle("Obs Format");
    setResizable(false);

    jButton1.setText("OK");
    jButton1.addActionListener(
        new java.awt.event.ActionListener() {
          public void actionPerformed(java.awt.event.ActionEvent evt) {
            OK_button_actionPerformed(evt);
          }
        });

    jButton2.setText("Cancel");
    jButton2.addActionListener(
        new java.awt.event.ActionListener() {
          public void actionPerformed(java.awt.event.ActionEvent evt) {
            Cancel_button_actionPerformed(evt);
          }
        });

    jLabel1.setText("obs format");

    jLabel2.setForeground(new java.awt.Color(0, 0, 255));
    jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel2.setText(
        "--- change this setting only with the prior agreement of your National Meteorological Service ---");

    jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

    buttonGroup1.add(jRadioButton1);
    jRadioButton1.setText("FM13");
    jRadioButton1.addItemListener(
        new java.awt.event.ItemListener() {
          public void itemStateChanged(java.awt.event.ItemEvent evt) {
            FM13_itemStateChanged(evt);
          }
        });

    buttonGroup1.add(jRadioButton2);
    jRadioButton2.setText("101 (semi compressed)");
    jRadioButton2.addItemListener(
        new java.awt.event.ItemListener() {
          public void itemStateChanged(java.awt.event.ItemEvent evt) {
            format_101_itemStateChanged(evt);
          }
        });

    buttonGroup1.add(jRadioButton7);
    jRadioButton7.setText("EUCAWS connected");
    jRadioButton7.addItemListener(
        new java.awt.event.ItemListener() {
          public void itemStateChanged(java.awt.event.ItemEvent evt) {
            AWS_itemStateChanged(evt);
          }
        });

    javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
    jPanel4.setLayout(jPanel4Layout);
    jPanel4Layout.setHorizontalGroup(
        jPanel4Layout
            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(
                jPanel4Layout
                    .createSequentialGroup()
                    .addContainerGap()
                    .addGroup(
                        jPanel4Layout
                            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(
                                jRadioButton2,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                163,
                                Short.MAX_VALUE)
                            .addComponent(
                                jRadioButton7,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                Short.MAX_VALUE)
                            .addComponent(
                                jRadioButton1,
                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                153,
                                javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(426, Short.MAX_VALUE)));
    jPanel4Layout.setVerticalGroup(
        jPanel4Layout
            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(
                javax.swing.GroupLayout.Alignment.TRAILING,
                jPanel4Layout
                    .createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jRadioButton1)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jRadioButton2)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jRadioButton7)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

    jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

    buttonGroup3.add(jRadioButton3);
    jRadioButton3.setText("uploads via EUCAWS (device's iridium modem) ");
    jRadioButton3.addItemListener(
        new java.awt.event.ItemListener() {
          public void itemStateChanged(java.awt.event.ItemEvent evt) {
            EUCAWS_uploads_via_AWS_itemStateChanged(evt);
          }
        });

    buttonGroup3.add(jRadioButton4);
    jRadioButton4.setText("uploads via TurboWin+ (Maintenance -> APR / APTR / AWSR settings)");
    jRadioButton4.addItemListener(
        new java.awt.event.ItemListener() {
          public void itemStateChanged(java.awt.event.ItemEvent evt) {
            EUCAWS_uploads_via_turbowin_itemStateChanged(evt);
          }
        });

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout
            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(
                jPanel1Layout
                    .createSequentialGroup()
                    .addContainerGap()
                    .addGroup(
                        jPanel1Layout
                            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton3)
                            .addComponent(jRadioButton4))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout
            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(
                jPanel1Layout
                    .createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jRadioButton3)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jRadioButton4)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

    jLabel3.setText("EUCAWS uploads");

    jLabel4.setText("EUCAWS SMD input");

    jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

    jCheckBox1.setText("add observer intials (OBS_ID) to SMD input");

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
        jPanel2Layout
            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(
                jPanel2Layout
                    .createSequentialGroup()
                    .addContainerGap()
                    .addComponent(
                        jCheckBox1,
                        javax.swing.GroupLayout.PREFERRED_SIZE,
                        533,
                        javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
    jPanel2Layout.setVerticalGroup(
        jPanel2Layout
            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(
                jPanel2Layout
                    .createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jCheckBox1)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout
            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(
                layout
                    .createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jSeparator1)
                    .addContainerGap())
            .addGroup(
                layout
                    .createSequentialGroup()
                    .addGap(313, 313, 313)
                    .addComponent(
                        jButton1,
                        javax.swing.GroupLayout.PREFERRED_SIZE,
                        80,
                        javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(
                        jButton2,
                        javax.swing.GroupLayout.PREFERRED_SIZE,
                        80,
                        javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(
                layout
                    .createSequentialGroup()
                    .addContainerGap(120, Short.MAX_VALUE)
                    .addGroup(
                        layout
                            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(
                                jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 599, Short.MAX_VALUE)
                            .addComponent(
                                jPanel4,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                Short.MAX_VALUE)
                            .addComponent(
                                jPanel1,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                Short.MAX_VALUE)
                            .addComponent(
                                jPanel2,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                Short.MAX_VALUE)
                            .addComponent(
                                jLabel4,
                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                253,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(
                                jLabel3,
                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                256,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(
                                jLabel1,
                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                255,
                                javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(121, Short.MAX_VALUE)));

    layout.linkSize(
        javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton1, jButton2});

    layout.setVerticalGroup(
        layout
            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(
                layout
                    .createSequentialGroup()
                    .addGap(65, 65, 65)
                    .addComponent(jLabel1)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(
                        jPanel4,
                        javax.swing.GroupLayout.PREFERRED_SIZE,
                        javax.swing.GroupLayout.DEFAULT_SIZE,
                        javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel2)
                    .addGap(47, 47, 47)
                    .addComponent(jLabel3)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(
                        jPanel1,
                        javax.swing.GroupLayout.PREFERRED_SIZE,
                        javax.swing.GroupLayout.DEFAULT_SIZE,
                        javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(30, 30, 30)
                    .addComponent(jLabel4)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(
                        jPanel2,
                        javax.swing.GroupLayout.PREFERRED_SIZE,
                        javax.swing.GroupLayout.DEFAULT_SIZE,
                        javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(
                        javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                    .addComponent(
                        jSeparator1,
                        javax.swing.GroupLayout.PREFERRED_SIZE,
                        javax.swing.GroupLayout.DEFAULT_SIZE,
                        javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(15, 15, 15)
                    .addGroup(
                        layout
                            .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(
                                jButton1,
                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                25,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(
                                jButton2,
                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                25,
                                javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(15, 15, 15)));

    pack();
  } // </editor-fold>//GEN-END:initComponents

  private void OK_button_actionPerformed(
      java.awt.event.ActionEvent evt) { // GEN-FIRST:event_OK_button_actionPerformed
    // TODO add your handling code here:
    boolean doorgaan;

    ////// obs format (FM13 or 101 or AWS) /////
    //
    if (jRadioButton1.isSelected() == true) // FM13
    {
      main.obs_format = main.FORMAT_FM13;
      doorgaan = true;
    } else if (jRadioButton2.isSelected() == true) // 101 format
    {
      main.obs_format = main.FORMAT_101;
      doorgaan = true;
    } else if (jRadioButton7.isSelected() == true) // AWS format
    {
      main.obs_format = main.FORMAT_AWS; // NB only for EUCAWS (OMC-140 must be 101 or FM13)
      main.eucaws_uploads_method = "";
      doorgaan = true;
    } else // obs format unknown
    {
      main.obs_format = "";
      doorgaan = false;

      String info = "Obs format unknown";
      JOptionPane.showMessageDialog(
          null, info, main.APPLICATION_NAME + " error", JOptionPane.WARNING_MESSAGE);
    } // else (obs format unknown)

    // obs format EUCAWS-AWS, so we have to check upload method too (eucaws or turbowin)
    //
    if ((doorgaan == true) && (main.obs_format.equals(main.FORMAT_AWS))) {
      /////// EUCAWS uploads (EUCAWS or TurboWin+)
      //
      if (jRadioButton3.isSelected() == true) // uploads via EUCAWS device (iridium modem)
      {
        main.eucaws_uploads_method = main.UPLOADS_VIA_EUCAWS;
        doorgaan = true;
      } else if (jRadioButton4.isSelected() == true) // uploads via TurboWin+ (ship's internet)
      {
        main.eucaws_uploads_method = main.UPLOADS_VIA_TURBOWIN;
        doorgaan = true;
      } else {
        main.eucaws_uploads_method = "";
        doorgaan = false;
      } // else

      // obs format = AWS and upload method unknown
      //
      if (doorgaan == false) {
        String info = "EUCAWS upload method unknown";
        JOptionPane.showMessageDialog(
            null, info, main.APPLICATION_NAME + " error", JOptionPane.WARNING_MESSAGE);
      }

      // check if OBS_ID must be added to SMD input
      //
      if (doorgaan == true) {
        if (jCheckBox1.isSelected()) {
          // add obs id (observer initials) to SMD input
          main.eucaws_obs_id = true;
        } else {
          main.eucaws_obs_id = false;
        }
      }
    } // if ( (doorgaan == true) && (main.obs_format.equals(main.FORMAT_AWS)) )

    if ((doorgaan == true) && (main.obs_format.equals(main.FORMAT_101))
        || ((main.obs_format.equals(main.FORMAT_AWS)
            && (main.eucaws_uploads_method.equals(main.UPLOADS_VIA_TURBOWIN))))) {
      // NB also eucaws + 'uploads via turbowin': format101 by default

      // only Windows virus scanners (so not Linux) tend to warn for the compression and
      // decompression programs
      OSDetector.OSType ostype = OSDetector.detect_OS();
      switch (ostype) {
        case WINDOWS:
          FORMAT_101.compression_exe = FORMAT_101.COMPRESSION_EXE_WIN;
          FORMAT_101.decompression_exe = FORMAT_101.DECOMPRESSION_EXE_WIN;

          String info_message =
              "In case you get a warning of your virus scanner: "
                  + "\""
                  + FORMAT_101.compression_exe
                  + "\""
                  + " and "
                  + "\""
                  + FORMAT_101.decompression_exe
                  + "\""
                  + " are essential parts of "
                  + main.APPLICATION_NAME
                  + " required for coding and decoding of format 101";
          JOptionPane.showMessageDialog(
              null, info_message, main.APPLICATION_NAME + " info", JOptionPane.INFORMATION_MESSAGE);
          break;
      } // switch (ostype)
    } // if ( (doorgaan == true) etc.

    //
    /////// write new (obs) configuration settings to file(s)
    //
    if (doorgaan == true) {
      // write meta (station) data to configuration files
      main.schrijf_configuratie_regels();

      /* message */
      String info = "Changes will take full effect after a TurboWin+ restart";
      JOptionPane.showMessageDialog(
          null, info, main.APPLICATION_NAME + " info", JOptionPane.INFORMATION_MESSAGE);

      /* close this obs format settings input page */
      setVisible(false);
      dispose();
    } // if (doorgaan == true)
  } // GEN-LAST:event_OK_button_actionPerformed

  private void Cancel_button_actionPerformed(
      java.awt.event.ActionEvent evt) { // GEN-FIRST:event_Cancel_button_actionPerformed
    // TODO add your handling code here:
    setVisible(false);
    dispose();
  } // GEN-LAST:event_Cancel_button_actionPerformed

  private void FM13_itemStateChanged(
      java.awt.event.ItemEvent evt) { // GEN-FIRST:event_FM13_itemStateChanged
    // TODO add your handling code here

    if (jRadioButton1.isSelected() == true) // FM13
    {
      buttonGroup3.clearSelection(); // NB better than jRadioButton3.setSelected(false);  and
      // jRadioButton4.setSelected(false);

      jRadioButton3.setEnabled(false); // uploads via eucaws
      jRadioButton4.setEnabled(false); // uploads via turbowin

      jCheckBox1.setSelected(false); // add OBS_ID to SMD input
      jCheckBox1.setEnabled(false); // add OBS_ID to SMD input
    } // if (jRadioButton1.isSelected() == true)
  } // GEN-LAST:event_FM13_itemStateChanged

  private void format_101_itemStateChanged(
      java.awt.event.ItemEvent evt) { // GEN-FIRST:event_format_101_itemStateChanged
    // TODO add your handling code here:

    if (jRadioButton2.isSelected() == true) // 101 format
    {
      buttonGroup3.clearSelection(); // NB better than jRadioButton3.setSelected(false);  and
      // jRadioButton4.setSelected(false);

      jRadioButton3.setEnabled(false); // uploads via eucaws
      jRadioButton4.setEnabled(false); // uploads via turbowin

      jCheckBox1.setSelected(false); // add OBS_ID to SMD input
      jCheckBox1.setEnabled(false); // add OBS_ID to SMD input
    } // if (jRadioButton2.isSelected() == true)
  } // GEN-LAST:event_format_101_itemStateChanged

  private void AWS_itemStateChanged(
      java.awt.event.ItemEvent evt) { // GEN-FIRST:event_AWS_itemStateChanged
    // TODO add your handling code here:

    if (jRadioButton7.isSelected() == true) // AWS format
    {
      jRadioButton3.setSelected(false); // uploads via eucaws
      jRadioButton4.setSelected(false); // uploads via turbowin

      jRadioButton3.setEnabled(true); // uploads via eucaws
      jRadioButton4.setEnabled(true); // uploads via turbowin

      jCheckBox1.setSelected(false); // add OBS_ID to SMD input
      jCheckBox1.setEnabled(true); // add OBS_ID to SMD input
    } // if (jRadioButton7.isSelected() == true)
  } // GEN-LAST:event_AWS_itemStateChanged

  private void EUCAWS_uploads_via_turbowin_itemStateChanged(
      java.awt.event.ItemEvent
          evt) { // GEN-FIRST:event_EUCAWS_uploads_via_turbowin_itemStateChanged
    // TODO add your handling code here:

    // obs uploads/sending via TurboWin+ then there is no SMD input (SMD input always via iridium
    // modem of the EUCAWS)

    jCheckBox1.setSelected(false); // add OBS_ID to SMD input
    jCheckBox1.setEnabled(false); // add OBS_ID to SMD input
  } // GEN-LAST:event_EUCAWS_uploads_via_turbowin_itemStateChanged

  private void EUCAWS_uploads_via_AWS_itemStateChanged(
      java.awt.event.ItemEvent evt) { // GEN-FIRST:event_EUCAWS_uploads_via_AWS_itemStateChanged
    // TODO add your handling code here:

    jCheckBox1.setEnabled(true); // add OBS_ID to SMD input
  } // GEN-LAST:event_EUCAWS_uploads_via_AWS_itemStateChanged

  private void initComponents2() {
    // initialisation
    jRadioButton1.setSelected(false); // FM13
    jRadioButton2.setSelected(false); // format 101
    jRadioButton3.setSelected(false); // uploads via eucaws
    jRadioButton4.setSelected(false); // uploads via turbowin
    jRadioButton7.setSelected(false); // AWS
    jCheckBox1.setSelected(false); // add OBS_ID to SMD input

    //
    ////// set (previous) selected values
    //

    // format (FM13 or AWS or format 101)
    if (main.obs_format.equals(main.FORMAT_FM13)) {
      jRadioButton1.setSelected(true);
    } else if (main.obs_format.equals(main.FORMAT_101)) {
      jRadioButton2.setSelected(true);
    } else if (main.obs_format.equals(main.FORMAT_AWS)) {
      jRadioButton7.setSelected(true);

      // EUCAWS uploads method
      if (main.eucaws_uploads_method.equals(main.UPLOADS_VIA_EUCAWS)) {
        jRadioButton3.setSelected(true); // uploads via eucaws
      } else if (main.eucaws_uploads_method.equals(main.UPLOADS_VIA_TURBOWIN)) {
        jRadioButton4.setSelected(true); // uploads via turbowin
      } else // default
      {
        jRadioButton3.setSelected(true); // uploads via eucaws
      }

      // EUCAWS, add OBS_ID to SMD input
      if (main.eucaws_obs_id) // boolean; add OBS_ID to SMD iput
      {
        jCheckBox1.setSelected(true);
      }
    } // else if (main.obs_format.equals(main.FORMAT_AWS))
  }

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Create and display the form */
    java.awt.EventQueue.invokeLater(
        new Runnable() {
          @Override
          public void run() {
            new myobsformat().setVisible(true);
          }
        });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.ButtonGroup buttonGroup1;
  private javax.swing.ButtonGroup buttonGroup3;
  private javax.swing.JButton jButton1;
  private javax.swing.JButton jButton2;
  private javax.swing.JCheckBox jCheckBox1;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JPanel jPanel4;
  private javax.swing.JRadioButton jRadioButton1;
  private javax.swing.JRadioButton jRadioButton2;
  private javax.swing.JRadioButton jRadioButton3;
  private javax.swing.JRadioButton jRadioButton4;
  private javax.swing.JRadioButton jRadioButton7;
  private javax.swing.JSeparator jSeparator1;
  // End of variables declaration//GEN-END:variables
}
