package turbowin;

import java.util.regex.Pattern;
import javax.swing.AbstractListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.ListModel;

/* NB max height deck cargo and diff. sll-wl can be set on this input page but also on the wind input page!   */

public final class mystationdata extends javax.swing.JFrame {

  /** Creates new form mystationdata */
  public mystationdata() {
    initComponents();
    initComponents2();
    initStationComponents();
    setLocation(main.x_pos_main_frame, main.y_pos_main_frame);
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT
   * modify this code. The content of this method is always regenerated by the Form Editor.
   */
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    buttonGroup1 = new javax.swing.ButtonGroup();
    buttonGroup2 = new javax.swing.ButtonGroup();
    buttonGroup3 = new javax.swing.ButtonGroup();
    buttonGroup5 = new javax.swing.ButtonGroup();
    buttonGroup6 = new javax.swing.ButtonGroup();
    buttonGroup4 = new javax.swing.ButtonGroup();
    jSeparator1 = new javax.swing.JSeparator();
    jButton1 = new javax.swing.JButton();
    jButton2 = new javax.swing.JButton();
    jPanel1 = new javax.swing.JPanel();
    jTextField1 = new javax.swing.JTextField();
    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    jTextField2 = new javax.swing.JTextField();
    jTextField10 = new javax.swing.JTextField();
    jLabel24 = new javax.swing.JLabel();
    jLabel5 = new javax.swing.JLabel();
    jPanel2 = new javax.swing.JPanel();
    jScrollPane2 = new javax.swing.JScrollPane();
    jList2 = new javax.swing.JList<>();
    jPanel3 = new javax.swing.JPanel();
    jRadioButton1 = new javax.swing.JRadioButton();
    jRadioButton2 = new javax.swing.JRadioButton();
    jRadioButton17 = new javax.swing.JRadioButton();
    jLabel11 = new javax.swing.JLabel();
    jLabel19 = new javax.swing.JLabel();
    jTextField7 = new javax.swing.JTextField();
    jTextField8 = new javax.swing.JTextField();
    jLabel6 = new javax.swing.JLabel();
    jRadioButton9 = new javax.swing.JRadioButton();
    jRadioButton10 = new javax.swing.JRadioButton();
    jLabel23 = new javax.swing.JLabel();
    jRadioButton18 = new javax.swing.JRadioButton();
    jRadioButton19 = new javax.swing.JRadioButton();
    jLabel14 = new javax.swing.JLabel();
    jTextField9 = new javax.swing.JTextField();
    jPanel4 = new javax.swing.JPanel();
    jLabel12 = new javax.swing.JLabel();
    jTextField5 = new javax.swing.JTextField();
    jLabel13 = new javax.swing.JLabel();
    jTextField6 = new javax.swing.JTextField();
    jLabel21 = new javax.swing.JLabel();
    jRadioButton11 = new javax.swing.JRadioButton();
    jRadioButton12 = new javax.swing.JRadioButton();
    jLabel3 = new javax.swing.JLabel();
    jTextField3 = new javax.swing.JTextField();
    jLabel7 = new javax.swing.JLabel();
    jLabel8 = new javax.swing.JLabel();
    jPanel6 = new javax.swing.JPanel();
    jLabel15 = new javax.swing.JLabel();
    jLabel16 = new javax.swing.JLabel();
    jRadioButton3 = new javax.swing.JRadioButton();
    jRadioButton4 = new javax.swing.JRadioButton();
    jRadioButton5 = new javax.swing.JRadioButton();
    jRadioButton6 = new javax.swing.JRadioButton();
    jRadioButton7 = new javax.swing.JRadioButton();
    jRadioButton8 = new javax.swing.JRadioButton();
    jRadioButton13 = new javax.swing.JRadioButton();
    jRadioButton14 = new javax.swing.JRadioButton();
    jRadioButton15 = new javax.swing.JRadioButton();
    jRadioButton16 = new javax.swing.JRadioButton();
    jLabel10 = new javax.swing.JLabel();
    jLabel20 = new javax.swing.JLabel();
    jLabel18 = new javax.swing.JLabel();
    jButton3 = new javax.swing.JButton();
    jLabel17 = new javax.swing.JLabel();
    jLabel22 = new javax.swing.JLabel();
    jLabel9 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setTitle("Station data");
    setMinimumSize(new java.awt.Dimension(1000, 700));
    setPreferredSize(new java.awt.Dimension(1000, 700));
    setResizable(false);

    jButton1.setText("OK");
    jButton1.addActionListener(
        new java.awt.event.ActionListener() {
          public void actionPerformed(java.awt.event.ActionEvent evt) {
            OK_button_actionPerformed(evt);
          }
        });

    jButton2.setText("Cancel");
    jButton2.addActionListener(
        new java.awt.event.ActionListener() {
          public void actionPerformed(java.awt.event.ActionEvent evt) {
            Cancel_button_actionPerformed(evt);
          }
        });

    jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

    jLabel1.setText("ship name");

    jLabel2.setText("IMO number");

    jLabel24.setText("station ID*");

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout
            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(
                jPanel1Layout
                    .createSequentialGroup()
                    .addContainerGap()
                    .addGroup(
                        jPanel1Layout
                            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(
                                jLabel2,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                Short.MAX_VALUE)
                            .addComponent(
                                jLabel24,
                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                67,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(
                                jLabel1,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                Short.MAX_VALUE))
                    .addPreferredGap(
                        javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                    .addGroup(
                        jPanel1Layout
                            .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(
                                jTextField1,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                335,
                                Short.MAX_VALUE)
                            .addComponent(jTextField2)
                            .addComponent(jTextField10))
                    .addContainerGap()));
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout
            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(
                jPanel1Layout
                    .createSequentialGroup()
                    .addContainerGap()
                    .addGroup(
                        jPanel1Layout
                            .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(
                                jTextField1,
                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(
                        jPanel1Layout
                            .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(
                                jTextField2,
                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(
                        jPanel1Layout
                            .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(
                                jTextField10,
                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(
                                jLabel24,
                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                14,
                                javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

    jLabel5.setText("ship data");

    jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

    jList2.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
    jScrollPane2.setViewportView(jList2);

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
        jPanel2Layout
            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(
                jPanel2Layout
                    .createSequentialGroup()
                    .addContainerGap()
                    .addComponent(
                        jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 413, Short.MAX_VALUE)
                    .addContainerGap()));
    jPanel2Layout.setVerticalGroup(
        jPanel2Layout
            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(
                jPanel2Layout
                    .createSequentialGroup()
                    .addContainerGap()
                    .addComponent(
                        jScrollPane2,
                        javax.swing.GroupLayout.PREFERRED_SIZE,
                        javax.swing.GroupLayout.DEFAULT_SIZE,
                        javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

    jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
    jPanel3.setPreferredSize(new java.awt.Dimension(387, 152));

    buttonGroup1.add(jRadioButton1);
    jRadioButton1.setText("estimated; true speed and true direction");

    buttonGroup1.add(jRadioButton2);
    jRadioButton2.setText("measured; apparent speed + app. dir. (OFF THE BOW, clockwise)*");

    buttonGroup1.add(jRadioButton17);
    jRadioButton17.setText("measured; true speed and true direction");

    jLabel11.setText("max. height deck cargo above SLL**  (metres, [0 - 100], rounded)");

    jLabel19.setText("difference SLL and WL (water line) (metres, [-10 - 50]****, rounded)");

    jLabel6.setText("wind speed units source (estimated/measured)");

    buttonGroup6.add(jRadioButton9);
    jRadioButton9.setText("knots");

    buttonGroup6.add(jRadioButton10);
    jRadioButton10.setText("m/s*");

    jLabel23.setText("wind speed units display (graphs/dashboards)");

    buttonGroup4.add(jRadioButton18);
    jRadioButton18.setText("knots");

    buttonGroup4.add(jRadioButton19);
    jRadioButton19.setText("m/s");

    jLabel14.setText("average height anemometer above WL (metres, [0-100], rounded)***");

    javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
    jPanel3.setLayout(jPanel3Layout);
    jPanel3Layout.setHorizontalGroup(
        jPanel3Layout
            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(
                jPanel3Layout
                    .createSequentialGroup()
                    .addContainerGap()
                    .addGroup(
                        jPanel3Layout
                            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(
                                jRadioButton2,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                Short.MAX_VALUE)
                            .addGroup(
                                jPanel3Layout
                                    .createSequentialGroup()
                                    .addComponent(
                                        jLabel14,
                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                        366,
                                        Short.MAX_VALUE)
                                    .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(
                                        jTextField9,
                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                        49,
                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(
                                jPanel3Layout
                                    .createSequentialGroup()
                                    .addComponent(
                                        jLabel11,
                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                        Short.MAX_VALUE)
                                    .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(
                                        jTextField7,
                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                        48,
                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(
                                jPanel3Layout
                                    .createSequentialGroup()
                                    .addComponent(jLabel19)
                                    .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                        Short.MAX_VALUE)
                                    .addComponent(
                                        jTextField8,
                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                        48,
                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(
                                javax.swing.GroupLayout.Alignment.TRAILING,
                                jPanel3Layout
                                    .createSequentialGroup()
                                    .addGroup(
                                        jPanel3Layout
                                            .createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(
                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                jPanel3Layout
                                                    .createSequentialGroup()
                                                    .addGroup(
                                                        jPanel3Layout
                                                            .createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment
                                                                    .TRAILING)
                                                            .addComponent(
                                                                jRadioButton17,
                                                                javax.swing.GroupLayout.Alignment
                                                                    .LEADING)
                                                            .addComponent(
                                                                jRadioButton1,
                                                                javax.swing.GroupLayout.Alignment
                                                                    .LEADING))
                                                    .addGap(0, 0, Short.MAX_VALUE))
                                            .addGroup(
                                                jPanel3Layout
                                                    .createSequentialGroup()
                                                    .addComponent(
                                                        jLabel6,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        276,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(
                                                        javax.swing.LayoutStyle.ComponentPlacement
                                                            .RELATED,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        Short.MAX_VALUE)
                                                    .addComponent(jRadioButton9))
                                            .addGroup(
                                                jPanel3Layout
                                                    .createSequentialGroup()
                                                    .addComponent(
                                                        jLabel23,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        276,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(
                                                        javax.swing.LayoutStyle.ComponentPlacement
                                                            .RELATED,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        Short.MAX_VALUE)
                                                    .addComponent(jRadioButton18)))
                                    .addGap(10, 10, 10)
                                    .addGroup(
                                        jPanel3Layout
                                            .createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jRadioButton19)
                                            .addComponent(jRadioButton10))))
                    .addContainerGap()));
    jPanel3Layout.setVerticalGroup(
        jPanel3Layout
            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(
                jPanel3Layout
                    .createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jRadioButton1)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jRadioButton2)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jRadioButton17)
                    .addGap(30, 30, 30)
                    .addGroup(
                        jPanel3Layout
                            .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(
                                jTextField7,
                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(
                        jPanel3Layout
                            .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(
                                jTextField8,
                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(27, 27, 27)
                    .addGroup(
                        jPanel3Layout
                            .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jRadioButton9)
                            .addComponent(jRadioButton10))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(
                        jPanel3Layout
                            .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(jRadioButton18)
                            .addComponent(jRadioButton19))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(
                        jPanel3Layout
                            .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(
                                jTextField9,
                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap()));

    jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
    jPanel4.setPreferredSize(new java.awt.Dimension(387, 107));

    jLabel12.setText("height of the barometer above SLL (metres, e.g. 20.8)");

    jLabel13.setText("distance of bottom of the keel to SLL (metres, e.g. 9.1)");

    jLabel21.setText("does the reading indicate MSL pressure*");

    buttonGroup5.add(jRadioButton11);
    jRadioButton11.setText("yes");

    buttonGroup5.add(jRadioButton12);
    jRadioButton12.setText("no*");

    jLabel3.setText("instrument correction (ic)** (hPa, e.g. -0.1)");

    javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
    jPanel4.setLayout(jPanel4Layout);
    jPanel4Layout.setHorizontalGroup(
        jPanel4Layout
            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(
                javax.swing.GroupLayout.Alignment.TRAILING,
                jPanel4Layout
                    .createSequentialGroup()
                    .addContainerGap()
                    .addGroup(
                        jPanel4Layout
                            .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(
                                jLabel3,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                Short.MAX_VALUE)
                            .addComponent(
                                jLabel12,
                                javax.swing.GroupLayout.Alignment.LEADING,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                Short.MAX_VALUE)
                            .addGroup(
                                javax.swing.GroupLayout.Alignment.LEADING,
                                jPanel4Layout
                                    .createSequentialGroup()
                                    .addComponent(
                                        jLabel21,
                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                        284,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                        31,
                                        Short.MAX_VALUE)
                                    .addComponent(jRadioButton11))
                            .addComponent(
                                jLabel13,
                                javax.swing.GroupLayout.Alignment.LEADING,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                Short.MAX_VALUE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(
                        jPanel4Layout
                            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(
                                jPanel4Layout
                                    .createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addComponent(jRadioButton12))
                            .addComponent(
                                jTextField5,
                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                48,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(
                                jTextField6,
                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                48,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(
                                jTextField3,
                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                48,
                                javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap()));
    jPanel4Layout.setVerticalGroup(
        jPanel4Layout
            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(
                jPanel4Layout
                    .createSequentialGroup()
                    .addContainerGap()
                    .addGroup(
                        jPanel4Layout
                            .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(
                                jTextField5,
                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(
                        jPanel4Layout
                            .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(
                                jTextField6,
                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(
                                jLabel13,
                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                14,
                                javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(
                        jPanel4Layout
                            .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(jRadioButton12)
                            .addComponent(jRadioButton11))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(
                        jPanel4Layout
                            .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(
                                jTextField3,
                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(28, Short.MAX_VALUE)));

    jLabel7.setText("wind meta data");

    jLabel8.setText("air pressure meta data");

    jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
    jPanel6.setPreferredSize(new java.awt.Dimension(387, 123));

    jLabel15.setText("air temp exposure");

    jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel16.setText("sea water temp exposure");

    buttonGroup2.add(jRadioButton3);
    jRadioButton3.setText("intake");

    buttonGroup2.add(jRadioButton4);
    jRadioButton4.setText("bucket");

    buttonGroup2.add(jRadioButton5);
    jRadioButton5.setText("hull contact sens.");

    buttonGroup2.add(jRadioButton6);
    jRadioButton6.setText("other");

    buttonGroup3.add(jRadioButton7);
    jRadioButton7.setText("sling psychro.");

    buttonGroup3.add(jRadioButton8);
    jRadioButton8.setText("marine screen");

    buttonGroup2.add(jRadioButton13);
    jRadioButton13.setText("trailing thermistor");

    buttonGroup2.add(jRadioButton14);
    jRadioButton14.setText("\"through hull\"sens.");

    buttonGroup2.add(jRadioButton15);
    jRadioButton15.setText("radiation thermo.");

    buttonGroup2.add(jRadioButton16);
    jRadioButton16.setText("bait tanks thermo.");

    javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
    jPanel6.setLayout(jPanel6Layout);
    jPanel6Layout.setHorizontalGroup(
        jPanel6Layout
            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(
                jPanel6Layout
                    .createSequentialGroup()
                    .addContainerGap()
                    .addGroup(
                        jPanel6Layout
                            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jRadioButton7)
                            .addComponent(jRadioButton8))
                    .addGap(18, 18, 18)
                    .addGroup(
                        jPanel6Layout
                            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(
                                jLabel16,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                Short.MAX_VALUE)
                            .addGroup(
                                jPanel6Layout
                                    .createSequentialGroup()
                                    .addGap(0, 0, Short.MAX_VALUE)
                                    .addGroup(
                                        jPanel6Layout
                                            .createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(
                                                jRadioButton6,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                135,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(
                                                jRadioButton16,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                135,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(
                                                jRadioButton15,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                135,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(
                                                jRadioButton14,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                135,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(
                                jPanel6Layout
                                    .createSequentialGroup()
                                    .addGroup(
                                        jPanel6Layout
                                            .createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(
                                                jRadioButton5,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                150,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(
                                                jRadioButton13,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                150,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(
                                                jRadioButton4,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                150,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(
                                                jRadioButton3,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                150,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(0, 0, Short.MAX_VALUE)))
                    .addGap(10, 10, 10)));
    jPanel6Layout.setVerticalGroup(
        jPanel6Layout
            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(
                jPanel6Layout
                    .createSequentialGroup()
                    .addContainerGap()
                    .addGroup(
                        jPanel6Layout
                            .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(jLabel15))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(
                        jPanel6Layout
                            .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton3)
                            .addComponent(
                                jRadioButton14,
                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                23,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButton7))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(
                        jPanel6Layout
                            .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton4)
                            .addComponent(jRadioButton15)
                            .addComponent(jRadioButton8))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(
                        jPanel6Layout
                            .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton5)
                            .addComponent(jRadioButton16))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(
                        jPanel6Layout
                            .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton6)
                            .addComponent(jRadioButton13))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

    jLabel10.setText("temperatures meta data");

    jLabel20.setText("* by definition if AWS with wind sensor is connected    ** Summer Load Line");

    jLabel18.setText("recruiting country");

    jButton3.setText("import");
    jButton3.addActionListener(
        new java.awt.event.ActionListener() {
          public void actionPerformed(java.awt.event.ActionEvent evt) {
            import_button_actionPerformed(evt);
          }
        });

    jLabel17.setText("* consult your PMO or National Meteorological Service");

    jLabel22.setText("* always \"no\" if a barometer or an AWS is connected");

    jLabel9.setText(
        "*** only if AWS with wind sensor is connected     **** negative if SLL below WL");

    jLabel4.setText(
        "** average over the whole calibration range, this is NOT the height correction (always 0.0 if AWS connected)");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout
            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(
                layout
                    .createSequentialGroup()
                    .addGroup(
                        layout
                            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(
                                layout
                                    .createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jSeparator1))
                            .addGroup(
                                javax.swing.GroupLayout.Alignment.TRAILING,
                                layout
                                    .createSequentialGroup()
                                    .addGroup(
                                        layout
                                            .createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(
                                                layout
                                                    .createSequentialGroup()
                                                    .addGap(10, 10, 10)
                                                    .addGroup(
                                                        layout
                                                            .createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment
                                                                    .LEADING)
                                                            .addComponent(
                                                                jPanel4,
                                                                javax.swing.GroupLayout
                                                                    .DEFAULT_SIZE,
                                                                429,
                                                                Short.MAX_VALUE)
                                                            .addGroup(
                                                                layout
                                                                    .createSequentialGroup()
                                                                    .addGroup(
                                                                        layout
                                                                            .createParallelGroup(
                                                                                javax.swing
                                                                                    .GroupLayout
                                                                                    .Alignment
                                                                                    .LEADING)
                                                                            .addGroup(
                                                                                layout
                                                                                    .createParallelGroup(
                                                                                        javax.swing
                                                                                            .GroupLayout
                                                                                            .Alignment
                                                                                            .LEADING)
                                                                                    .addComponent(
                                                                                        jLabel17,
                                                                                        javax.swing
                                                                                            .GroupLayout
                                                                                            .Alignment
                                                                                            .TRAILING,
                                                                                        javax.swing
                                                                                            .GroupLayout
                                                                                            .PREFERRED_SIZE,
                                                                                        401,
                                                                                        javax.swing
                                                                                            .GroupLayout
                                                                                            .PREFERRED_SIZE)
                                                                                    .addComponent(
                                                                                        jLabel18,
                                                                                        javax.swing
                                                                                            .GroupLayout
                                                                                            .PREFERRED_SIZE,
                                                                                        199,
                                                                                        javax.swing
                                                                                            .GroupLayout
                                                                                            .PREFERRED_SIZE))
                                                                            .addComponent(
                                                                                jLabel5,
                                                                                javax.swing
                                                                                    .GroupLayout
                                                                                    .PREFERRED_SIZE,
                                                                                202,
                                                                                javax.swing
                                                                                    .GroupLayout
                                                                                    .PREFERRED_SIZE))
                                                                    .addGap(
                                                                        0, 0, Short.MAX_VALUE))))
                                            .addGroup(
                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                layout
                                                    .createSequentialGroup()
                                                    .addContainerGap()
                                                    .addGroup(
                                                        layout
                                                            .createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment
                                                                    .LEADING)
                                                            .addComponent(
                                                                jPanel2,
                                                                javax.swing.GroupLayout.Alignment
                                                                    .TRAILING,
                                                                javax.swing.GroupLayout
                                                                    .PREFERRED_SIZE,
                                                                javax.swing.GroupLayout
                                                                    .DEFAULT_SIZE,
                                                                javax.swing.GroupLayout
                                                                    .PREFERRED_SIZE)
                                                            .addComponent(
                                                                jPanel1,
                                                                javax.swing.GroupLayout.Alignment
                                                                    .TRAILING,
                                                                javax.swing.GroupLayout
                                                                    .PREFERRED_SIZE,
                                                                javax.swing.GroupLayout
                                                                    .DEFAULT_SIZE,
                                                                javax.swing.GroupLayout
                                                                    .PREFERRED_SIZE))))
                                    .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                        15,
                                        Short.MAX_VALUE)
                                    .addGroup(
                                        layout
                                            .createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(
                                                jPanel3,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                437,
                                                Short.MAX_VALUE)
                                            .addComponent(
                                                jLabel9,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                Short.MAX_VALUE)
                                            .addComponent(
                                                jLabel20,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                434,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(
                                                jPanel6,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                437,
                                                Short.MAX_VALUE)
                                            .addComponent(
                                                jLabel7,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                219,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(
                                                jLabel10,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                232,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(10, 10, 10)))
                    .addContainerGap())
            .addGroup(
                layout
                    .createSequentialGroup()
                    .addGap(354, 354, 354)
                    .addComponent(
                        jButton1,
                        javax.swing.GroupLayout.PREFERRED_SIZE,
                        80,
                        javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(
                        jButton2,
                        javax.swing.GroupLayout.PREFERRED_SIZE,
                        80,
                        javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(
                        jButton3,
                        javax.swing.GroupLayout.PREFERRED_SIZE,
                        80,
                        javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(
                layout
                    .createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addGroup(
                        layout
                            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(
                                jLabel8,
                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                222,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(
                                jLabel22,
                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                425,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(
                                jLabel4,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                Short.MAX_VALUE))
                    .addGap(16, 16, 16)));
    layout.setVerticalGroup(
        layout
            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(
                layout
                    .createSequentialGroup()
                    .addContainerGap()
                    .addGroup(
                        layout
                            .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(
                                jLabel7,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                Short.MAX_VALUE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(
                        layout
                            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(
                                layout
                                    .createSequentialGroup()
                                    .addComponent(
                                        jPanel1,
                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel17)
                                    .addGap(25, 25, 25)
                                    .addComponent(jLabel18)
                                    .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(
                                        jPanel2,
                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(25, 25, 25)
                                    .addGroup(
                                        layout
                                            .createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel10)))
                            .addGroup(
                                layout
                                    .createSequentialGroup()
                                    .addComponent(
                                        jPanel3,
                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                        281,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel20)
                                    .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel9)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(
                        layout
                            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(
                                jPanel4,
                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                143,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(
                                jPanel6,
                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                143,
                                javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel22)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel4)
                    .addPreferredGap(
                        javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                    .addComponent(
                        jSeparator1,
                        javax.swing.GroupLayout.PREFERRED_SIZE,
                        javax.swing.GroupLayout.DEFAULT_SIZE,
                        javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(15, 15, 15)
                    .addGroup(
                        layout
                            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(
                                jButton3,
                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                25,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(
                                javax.swing.GroupLayout.Alignment.TRAILING,
                                layout
                                    .createSequentialGroup()
                                    .addGroup(
                                        layout
                                            .createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(
                                                jButton1,
                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                25,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(
                                                jButton2,
                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                25,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(15, 15, 15)))));

    pack();
  } // </editor-fold>//GEN-END:initComponents

  private void lees_iso_landen_codes() {
    /* NB input/output GUI always via a SwingWorker (Core Java Volume 1 bld 795 e.v.; Volume 2 bld 37, 215) */

    for (int i = 0; i < MAX_AANTAL_ISO_LANDEN_REGELS; i++) {
      iso_landen_regels[i] = "";
    }
    StationDataIsoCountriesWorkflow.start(this);
  }

  void updateIsoCountryList(String[] records) {
    iso_landen_regels = records;

    // NB open the GUI form, select the JList component, go to Properties -> Code and set "Type
    // Parameters" property to <String>.

    // jList2.setModel(new javax.swing.AbstractListModel()
    ListModel<String> iso_landen_model =
        new AbstractListModel<String>() {
          String[] strings = {
            records[0],
            records[1],
            records[2],
            records[3],
            records[4],
            records[5],
            records[6],
            records[7],
            records[8],
            records[9],
            records[10],
            records[11],
            records[12],
            records[13],
            records[14],
            records[15],
            records[16],
            records[17],
            records[18],
            records[19],
            records[20],
            records[21],
            records[22],
            records[23],
            records[24],
            records[25],
            records[26],
            records[27],
            records[28],
            records[29],
            records[30],
            records[31],
            records[32],
            records[33],
            records[34],
            records[35],
            records[36],
            records[37],
            records[38],
            records[39],
            records[40],
            records[41],
            records[42],
            records[43],
            records[44],
            records[45],
            records[46],
            records[47],
            records[48],
            records[49],
            records[50],
            records[51],
            records[52],
            records[53],
            records[54],
            records[55],
            records[56],
            records[57],
            records[58],
            records[59],
            records[60],
            records[61],
            records[62],
            records[63],
            records[64],
            records[65],
            records[66],
            records[67],
            records[68],
            records[69],
            records[70],
            records[71],
            records[72],
            records[73],
            records[74],
            records[75],
            records[76],
            records[77],
            records[78],
            records[79],
            records[80],
            records[81],
            records[82],
            records[83],
            records[84],
            records[85],
            records[86],
            records[87],
            records[88],
            records[89],
            records[90],
            records[91],
            records[92],
            records[93],
            records[94],
            records[95],
            records[96],
            records[97],
            records[98],
            records[99],
            records[100],
            records[101],
            records[102],
            records[103],
            records[104],
            records[105],
            records[106],
            records[107],
            records[108],
            records[109],
            records[110],
            records[111],
            records[112],
            records[113],
            records[114],
            records[115],
            records[116],
            records[117],
            records[118],
            records[119],
            records[120],
            records[121],
            records[122],
            records[123],
            records[124],
            records[125],
            records[126],
            records[127],
            records[128],
            records[129],
            records[130],
            records[131],
            records[132],
            records[133],
            records[134],
            records[135],
            records[136],
            records[137],
            records[138],
            records[139],
            records[140],
            records[141],
            records[142],
            records[143],
            records[144],
            records[145],
            records[146],
            records[147],
            records[148],
            records[149],
            records[150],
            records[151],
            records[152],
            records[153],
            records[154],
            records[155],
            records[156],
            records[157],
            records[158],
            records[159],
            records[160],
            records[161],
            records[162],
            records[163],
            records[164],
            records[165],
            records[166],
            records[167],
            records[168],
            records[169],
            records[170],
            records[171],
            records[172],
            records[173],
            records[174],
            records[175],
            records[176],
            records[177],
            records[178],
            records[179],
            records[180],
            records[181],
            records[182],
            records[183],
            records[184],
            records[185],
            records[186],
            records[187],
            records[188],
            records[189],
            records[190],
            records[191],
            records[192],
            records[193],
            records[194],
            records[195],
            records[196],
            records[197],
            records[198],
            records[199],
            records[200],
            records[201],
            records[202],
            records[203],
            records[204],
            records[205],
            records[206],
            records[207],
            records[208],
            records[209],
            records[210],
            records[211],
            records[212],
            records[213],
            records[214],
            records[215],
            records[216],
            records[217],
            records[218],
            records[219],
            records[220],
            records[221],
            records[222],
            records[223],
            records[224],
            records[225],
            records[226],
            records[227],
            records[228],
            records[229],
            records[230],
            records[231],
            records[232],
            records[233],
            records[234],
            records[235],
            records[236],
            records[237],
            records[238],
            records[239],
            records[240],
            records[241],
            records[242],
            records[243],
            records[244],
            records[245],
            records[246],
            records[247],
            records[248],
            records[249],
            records[250],
            records[251],
            records[252],
            records[253],
            records[254],
            records[255],
            records[256],
            records[257],
            records[258],
            records[259],
            records[260],
            records[261],
            records[262],
            records[263],
            records[264],
            records[265],
            records[266],
            records[267],
            records[268],
            records[269],
            records[270],
            records[271],
            records[272],
            records[273],
            records[274],
            records[275],
            records[276],
            records[277],
            records[278],
            records[279],
            records[280],
            records[281],
            records[282],
            records[283],
            records[284],
            records[285],
            records[286],
            records[287],
            records[288],
            records[289],
            records[290],
            records[291],
            records[292],
            records[293],
            records[294],
            records[295],
            records[296],
            records[297],
            records[298],
            records[299],
          };

          @Override
          public int getSize() {
            return strings.length;
          }

          @Override
          public String getElementAt(int i) {
            return strings[i];
          }
        };

    // set model
    jList2.setModel(iso_landen_model);

    // set selected recruiting counry
    jList2.setSelectedValue(main.recruiting_country.trim(), true);

    // to be sure selected recruiting counry is visible
    int hulp_index = jList2.getSelectedIndex();
    jList2.ensureIndexIsVisible(hulp_index);
  }

  String[] getIsoCountryRecords() {
    return iso_landen_regels;
  }

  private void OK_button_actionPerformed(
      java.awt.event.ActionEvent evt) { // GEN-FIRST:event_OK_button_actionPerformed
    // TODO add your handling code here:

    boolean doorgaan = true;
    String info = "";

    /* read meta data components */
    main.ship_name = jTextField1.getText().trim();
    main.imo_number = jTextField2.getText().trim();
    // main.call_sign                = jTextField3.getText().trim().toUpperCase();
    // main.masked_call_sign         = jTextField4.getText().trim().toUpperCase();
    main.barometer_above_sll = jTextField5.getText().trim();
    main.keel_sll = jTextField6.getText().trim();
    main.max_height_deck_cargo = jTextField7.getText().trim();
    main.diff_sll_wl = jTextField8.getText().trim();
    main.station_ID = jTextField10.getText().trim();
    main.barometer_instrument_correction = jTextField3.getText().trim();

    if (jRadioButton1.isSelected() == true) main.wind_source = main.ESTIMATED_TRUE;
    else if (jRadioButton2.isSelected() == true) main.wind_source = main.MEASURED_OFF_BOW;
    else if (jRadioButton17.isSelected() == true) main.wind_source = main.MEASURED_TRUE;

    // wind units observed/measured
    if (jRadioButton9.isSelected() == true) main.wind_units = main.KNOTS;
    else if (jRadioButton10.isSelected() == true) main.wind_units = main.M_S;

    // wind units graphs/dashboard
    if (jRadioButton18.isSelected() == true) {
      main.wind_units_dashboard = main.KNOTS;
    } else if (jRadioButton19.isSelected() == true) {
      main.wind_units_dashboard = main.M_S;
    }

    // average height anemometer above WL
    main.height_anemometer = jTextField9.getText().trim();

    if (jRadioButton3.isSelected() == true) main.sst_exposure = main.INTAKE;
    else if (jRadioButton4.isSelected() == true) main.sst_exposure = main.BUCKET;
    else if (jRadioButton5.isSelected() == true) main.sst_exposure = main.HULL_CONTACT_SENSOR;
    else if (jRadioButton6.isSelected() == true) main.sst_exposure = main.OTHER;
    else if (jRadioButton13.isSelected() == true) main.sst_exposure = main.TRAILING_THERMISTOR;
    else if (jRadioButton14.isSelected() == true) main.sst_exposure = main.THROUGH_HULL_SENSOR;
    else if (jRadioButton15.isSelected() == true) main.sst_exposure = main.RADIATION_THERMOMETER;
    else if (jRadioButton16.isSelected() == true) main.sst_exposure = main.BAIT_TANKS_THERMOMETER;

    if (jRadioButton7.isSelected() == true) main.air_temp_exposure = main.SLING_PSYCHROMETER;
    else if (jRadioButton8.isSelected() == true) main.air_temp_exposure = main.MARINE_SCREEN;

    // turned off, always UTC taken, if necessary after conversion from other time zone to UTC (see
    // function check_and_set_datetime() in main.java
    //
    // if (jRadioButton9.isSelected() == true)
    //   main.time_zone_computer = main.TIME_ZONE_COMPUTER_UTC;
    // else if (jRadioButton10.isSelected() == true)
    //   main.time_zone_computer = main.TIME_ZONE_COMPUTER_OTHER;
    main.time_zone_computer = "";

    if (jRadioButton11.isSelected() == true)
      main.pressure_reading_msl_yes_no = main.PRESSURE_READING_MSL_YES;
    else if (jRadioButton12.isSelected() == true)
      main.pressure_reading_msl_yes_no = main.PRESSURE_READING_MSL_NO;

    if (jList2.getSelectedValue() != null) // nothing selected, returns null
    main.recruiting_country = (String) jList2.getSelectedValue();
    else main.recruiting_country = "";

    // turned off, now fixed on SEA_AND_SWELL_ESTIMATED
    // if (jList1.getSelectedValue() != null)                                 // nothing selected,
    // returns null
    //   main.method_waves             = (String)jList1.getSelectedValue();
    // else
    //   main.method_waves             = "";
    main.method_waves = main.SEA_AND_SWELL_ESTIMATED;

    /* checks */
    if (main.ship_name.trim().equals("") == true || main.ship_name.trim().length() < 2) {
      info = "Ship name: unknown/not valid";
    }
    // from version 4.2: IMO not mandatory anymore
    // else if (main.imo_number.trim().equals("") == true || main.imo_number.trim().length() < 2)
    // {
    //   info = "IMO number: unknown/not valid";
    // }

    // else if (main.call_sign.trim().equals("") == true || main.call_sign.trim().length() < 2)
    // {
    //   info = "Call sign: unknown/not valid";
    // }

    else if (main.station_ID.trim().equals("") == true || main.station_ID.trim().length() < 2) {
      info = "station ID: unknown/not valid";
    }

    // else if (main.time_zone_computer.trim().equals("") == true ||
    // main.time_zone_computer.trim().length() < 2)
    // {
    //   info = "Time zone computer: unknown/not valid";
    // }
    else if (main.recruiting_country.trim().equals("") == true
        || main.recruiting_country.trim().length() < 2) {
      info = "Recruiting country: unknown/not valid";
    } else if (main.wind_source.trim().equals("") == true || main.wind_source.trim().length() < 2) {
      info = "Wind source (measured/estimated): unknown/not valid";
    } else if (main.max_height_deck_cargo.trim().equals("") == true
        || main.max_height_deck_cargo.trim().length() < 1) {
      info = "Maximum height deck cargo: unknown/not valid";
    } else if (main.diff_sll_wl.trim().equals("") == true || main.diff_sll_wl.trim().length() < 1) {
      info = "Difference SLL and water line: unknown/not valid";
    } else if (main.wind_units.trim().equals("") == true || main.wind_units.trim().length() < 2) {
      info = "Wind speed units measured/estimated unknown/not valid";
    }

    // only for AWS ??
    // else if (main.wind_units_dashboard.trim().equals("") == true ||
    // main.wind_units_dashboard.trim().length() < 2)
    // {
    //   info = "Wind speed units dashboard unknown/not valid";
    // }

    else if (main.pressure_reading_msl_yes_no.trim().equals("") == true
        || main.pressure_reading_msl_yes_no.trim().length() < 2) {
      info = "Air pressure reading indication: unknown/not valid";
    } else if (main.barometer_above_sll.trim().equals("") == true
        || main.barometer_above_sll.trim().length() < 1) {
      info = "Height of the barometer above SLL: unknown/not valid";
    } else if (main.keel_sll.trim().equals("") == true || main.keel_sll.trim().length() < 1) {
      info = "Distance of bottom of the keel to SLL: unknown/not valid";
    } else if (main.air_temp_exposure.trim().equals("") == true
        || main.air_temp_exposure.trim().length() < 2) {
      info = "Air temp exposure: unknown/not valid";
    } else if (main.sst_exposure.trim().equals("") == true
        || main.sst_exposure.trim().length() < 2) {
      info = "Sea water temp exposure: unknown/not valid";
    } else if ((main.pressure_reading_msl_yes_no.equals(main.PRESSURE_READING_MSL_YES) == true)
        && (main.RS232_connection_mode != 0)) // AWS or barometer connected
    {
      info =
          "If AWS or barometer connected (Maintenance -> Serial/USB/LAN connection settings) please select: \"does the reading indicate MSL pressure = no\"\n";
    }
    /////// if info/warning available -> pop-up message //////
    if (info.compareTo("") != 0) {
      doorgaan = false;
      JOptionPane.showMessageDialog(
          null, info, main.APPLICATION_NAME + " error", JOptionPane.WARNING_MESSAGE);
    } else {
      doorgaan = true;
    }
    // station ID (SOT ID) extra check (all char in range a-z or A-Z or 0-9)
    if (doorgaan == true) {
      if (main.station_ID.trim().equals("") == false) {
        badChar = Pattern.compile("[^A-Za-z0-9]");
        if (badChar.matcher(main.station_ID.trim()).find()) {
          info = "station ID: invalid character(s)";
          JOptionPane.showMessageDialog(
              null, info, main.APPLICATION_NAME + " error", JOptionPane.WARNING_MESSAGE);
          doorgaan = false;
          main.station_ID = "";
        }
      }
    }

    // station ID (SOT ID) extra check (string length must be 7)
    //
    // NOTE BUT.. observers can also insert call sign in this field so maximum length = 7
    //
    if (doorgaan == true) {
      if (main.station_ID.trim().equals("") == false) {
        // if (main.station_ID.trim().length() != 7)
        if (main.station_ID.trim().length() > 7) {
          info = "station ID: invalid string length";
          JOptionPane.showMessageDialog(
              null, info, main.APPLICATION_NAME + " error", JOptionPane.WARNING_MESSAGE);
          doorgaan = false;
          main.station_ID = "";
        }
      }
    }

    if (doorgaan == true) {
      // max. height deck cargo
      //
      try {
        int int_max_height_deck_cargo = Integer.parseInt(main.max_height_deck_cargo.trim());

        if (int_max_height_deck_cargo < 0 || int_max_height_deck_cargo > 100) {
          info = "Max. height deck cargo above SLL must be in range 0 - 100 metres (rounded)";
          JOptionPane.showMessageDialog(
              null, info, main.APPLICATION_NAME + " error", JOptionPane.WARNING_MESSAGE);
          doorgaan = false;
        }
      } // try
      catch (NumberFormatException e) {
        info = "Max. height deck cargo above SLL must be in range 0 - 100 metres (rounded)";
        JOptionPane.showMessageDialog(
            null, info, main.APPLICATION_NAME + " error", JOptionPane.WARNING_MESSAGE);
        doorgaan = false;
      } // catch
    } // if (doorgaan == true)

    if (doorgaan == true) {
      // difference SLL and water line
      //
      try {
        int int_diff_sll_wl = Integer.parseInt(main.diff_sll_wl.trim());

        if (int_diff_sll_wl < -10 || int_diff_sll_wl > 50) {
          info = "Difference SLL and water line must be in range -10 - 50 metres (rounded)";
          JOptionPane.showMessageDialog(
              null, info, main.APPLICATION_NAME + " error", JOptionPane.WARNING_MESSAGE);
          doorgaan = false;
        }
      } // try
      catch (NumberFormatException e) {
        info = "Difference SLL and water line must be in range -10 - 50 metres (rounded)";
        JOptionPane.showMessageDialog(
            null, info, main.APPLICATION_NAME + " error", JOptionPane.WARNING_MESSAGE);
        doorgaan = false;
      } // catch
    } // if (doorgaan == true)

    if (doorgaan == true) {
      // height of the barometer above SLL
      //
      try {
        // int int_barometer_above_sll = Integer.parseInt(main.barometer_above_sll.trim());
        float float_barometer_above_sll = Float.parseFloat(main.barometer_above_sll.trim());

        // if (int_barometer_above_sll < 0 || int_barometer_above_sll > 50)
        if (float_barometer_above_sll < 0.0 || float_barometer_above_sll > 100.0) {
          info = "Height of the barometer above SLL must be in range 0.0 - 100.0 metres";
          JOptionPane.showMessageDialog(
              null, info, main.APPLICATION_NAME + " error", JOptionPane.WARNING_MESSAGE);
          doorgaan = false;
        }
      } // try
      catch (NumberFormatException e) {
        info = "Height of the barometer above SLL must be in range 0.0 - 100.0 metres";
        JOptionPane.showMessageDialog(
            null, info, main.APPLICATION_NAME + " error", JOptionPane.WARNING_MESSAGE);
        doorgaan = false;
      } // catch
    } // if (doorgaan == true)

    if (doorgaan == true) {
      // distance of bottom of the keel to SLL
      //
      try {
        // int int_keel_sll = Integer.parseInt(main.keel_sll.trim());
        float float_keel_sll = Float.parseFloat(main.keel_sll.trim());

        // if (int_keel_sll < 0 || int_keel_sll > 50)
        if (float_keel_sll < 0 || float_keel_sll > 50) {
          info = "Distance of bottom of the keel to SLL must be in range 0.0 - 50.0 metres";
          JOptionPane.showMessageDialog(
              null, info, main.APPLICATION_NAME + " error", JOptionPane.WARNING_MESSAGE);
          doorgaan = false;
        }
      } // try
      catch (NumberFormatException e) {
        info = "Distance of bottom of the keel to SLL must be in range 0.0 - 50.0 metres";
        JOptionPane.showMessageDialog(
            null, info, main.APPLICATION_NAME + " error", JOptionPane.WARNING_MESSAGE);
        doorgaan = false;
      } // catch
    } // if (doorgaan == true)

    if (doorgaan == true) {
      // barometer instrument correction
      //
      try {
        double double_barometer_instrument_correction =
            Double.parseDouble(main.barometer_instrument_correction.trim());
        if (double_barometer_instrument_correction < -4.0
            || double_barometer_instrument_correction > 4.0) {
          JOptionPane.showMessageDialog(
              null,
              "barometer instrument correction must be in range -4.0 - 4.0",
              main.APPLICATION_NAME + " error",
              JOptionPane.WARNING_MESSAGE);
          doorgaan = false;
        }
      } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(
            null,
            "barometer instrument correction must be in range -4.0 - 4.0",
            main.APPLICATION_NAME + " error",
            JOptionPane.WARNING_MESSAGE);
        doorgaan = false;
      }
    } //  if (doorgaan == true)

    if (doorgaan == true) {

      if (main.recruiting_country.indexOf("UNITED KINGDOM") != -1) {
        // JOptionPane.showMessageDialog(null, main.recruiting_country, main.APPLICATION_NAME + "
        // test uk ok", JOptionPane.WARNING_MESSAGE);

        // see also myemailsettings.java
        // NB omdat na invullen van dit scherm niet direct emailsettings invul scherm geopend wordt
        //    hier direct de obs_email_subject zetten en vastleggen in configuratie file voor UK
        // recruited ships
        main.obs_email_subject = main.UK_OBS_EMAIL_SUBJECT;
      }
    }

    if (doorgaan == true) {
      // write meta (station) data to muffins or configuration files
      main.schrijf_configuratie_regels();

      /* update station ID and ship name on main screen progress */
      main.ID_fields_update();

      /* message */
      // info = "Changes will take effect inmediatelly. Not necessary to restart";
      info = "Changes will take full effect after a TurboWin+ restart";
      JOptionPane.showMessageDialog(
          null, info, main.APPLICATION_NAME + " info", JOptionPane.INFORMATION_MESSAGE);

      /* close input page */
      setVisible(false);
      dispose();
    } // if (doorgaan == true)
  } // GEN-LAST:event_OK_button_actionPerformed

  private void initComponents2() {
    jTextField1.setName("ship_name");
    jTextField2.setName("imo_number");
    jTextField5.setName("barometer_height");
    jTextField6.setName("keel_distance");
    jTextField7.setName("max_height_deck_cargo");
    jTextField8.setName("difference_sll_wl");
    jTextField10.setName("station_id");
  }

  private void Cancel_button_actionPerformed(
      java.awt.event.ActionEvent evt) { // GEN-FIRST:event_Cancel_button_actionPerformed
    // TODO add your handling code here:

    /* close input page */
    setVisible(false);
    dispose();
  } // GEN-LAST:event_Cancel_button_actionPerformed

  private void import_button_actionPerformed(
      java.awt.event.ActionEvent evt) { // GEN-FIRST:event_import_button_actionPerformed
    // TODO add your handling code here:

    boolean doorgaan = true;
    // String configuration_dir;

    String info =
        "If this is not the first time use of this program then you can import previous (automatically) saved station data\n";
    info += "The location of the station data file depends on the TurboWin+ installation folder\n";
    info +=
        "If the location of the station data file (configuration.txt) is not known you can do, before importing, a file search on your disk outside TurboWin+";

    int reply =
        JOptionPane.showConfirmDialog(
            null,
            info,
            main.APPLICATION_NAME,
            JOptionPane.OK_CANCEL_OPTION,
            JOptionPane.PLAIN_MESSAGE);
    if (reply == JOptionPane.CANCEL_OPTION) {
      doorgaan = false;
    }

    if (doorgaan == true) {
      // pop-up the file chooser dialog box
      JFileChooser chooser = new JFileChooser();

      // Add a custom file filter and disable the default "(Accept All)" file filter.
      chooser.addChoosableFileFilter(new myfilefilter()); // zie myfilefilter.java
      chooser.setAcceptAllFileFilterUsed(false);

      int result = chooser.showOpenDialog(mystationdata.this);
      if (result == JFileChooser.APPROVE_OPTION) {
        import_file = chooser.getSelectedFile().getPath();

        StationDataImportWorkflow.start(import_file, this::initStationComponents);

        // write meta (station) data to muffins or configuration files
        main.schrijf_configuratie_regels();
      } // if (result == JFileChooser.APPROVE_OPTION
    } // if (doorgaan == true)
  } // GEN-LAST:event_import_button_actionPerformed

  private void initStationComponents() {
    // recruiting country (NB in java not possible to sort directly)
    lees_iso_landen_codes(); // in this function jList2 is populated, not possible to fill List2
    // ship name
    jTextField1.setText(main.ship_name.trim());
    // IMO nummer
    jTextField2.setText(main.imo_number.trim());
    // station ID (SOT ID)
    jTextField10.setText(main.station_ID.trim());
    // wind meta data
    if (main.wind_source.trim().indexOf("estimated") != -1) jRadioButton1.setSelected(true);
    else if ((main.wind_source.trim().indexOf("measured") != -1)
        && (main.wind_source.trim().indexOf("apparent") != -1)) jRadioButton2.setSelected(true);
    else if ((main.wind_source.trim().indexOf("measured") != -1)
        && (main.wind_source.trim().indexOf("true") != -1)) jRadioButton17.setSelected(true);

    jTextField7.setText(main.max_height_deck_cargo.trim());
    jTextField8.setText(main.diff_sll_wl.trim());

    if (main.wind_units.trim().indexOf(main.KNOTS) != -1) jRadioButton9.setSelected(true);
    else if (main.wind_units.trim().indexOf(main.M_S) != -1) jRadioButton10.setSelected(true);
    else // if nothing selected before set selection to "KNOTS"
    jRadioButton9.setSelected(true);
    // JOptionPane.showMessageDialog(null, main.wind_units, main.APPLICATION_NAME + " TEST",
    // JOptionPane.WARNING_MESSAGE);

    if (main.wind_units_dashboard.trim().indexOf(main.KNOTS) != -1) {
      jRadioButton18.setSelected(true);
    } else if (main.wind_units_dashboard.trim().indexOf(main.M_S) != -1) {
      jRadioButton19.setSelected(true);
    } else // if nothing selected before set selection to "KNOTS"
    {
      jRadioButton18.setSelected(true);
    }

    // height anemometer above the WL
    //
    jTextField9.setText(main.height_anemometer.trim());

    // air pressure meta data
    //
    jTextField5.setText(main.barometer_above_sll.trim());
    jTextField6.setText(main.keel_sll.trim());
    if (main.pressure_reading_msl_yes_no.trim().equals(main.PRESSURE_READING_MSL_YES))
      jRadioButton11.setSelected(true);
    else if (main.pressure_reading_msl_yes_no.trim().equals(main.PRESSURE_READING_MSL_NO))
      jRadioButton12.setSelected(true);

    if (main.barometer_instrument_correction.compareTo("") != 0) {
      jTextField3.setText(main.barometer_instrument_correction);
    } else {
      // as agreed PB July 2024, now put 0.0 as default here
      jTextField3.setText("0.0");
    }

    // air temp exposure
    //
    if (main.air_temp_exposure.trim().equals(main.SLING_PSYCHROMETER))
      jRadioButton7.setSelected(true);
    else if (main.air_temp_exposure.trim().equals(main.MARINE_SCREEN))
      jRadioButton8.setSelected(true);

    // sst exposure
    //
    if (main.sst_exposure.trim().equals(main.INTAKE)) jRadioButton3.setSelected(true);
    else if (main.sst_exposure.trim().equals(main.BUCKET)) jRadioButton4.setSelected(true);
    else if (main.sst_exposure.trim().equals(main.HULL_CONTACT_SENSOR))
      jRadioButton5.setSelected(true);
    else if (main.sst_exposure.trim().equals(main.OTHER)) jRadioButton6.setSelected(true);
    else if (main.sst_exposure.trim().equals(main.TRAILING_THERMISTOR))
      jRadioButton13.setSelected(true);
    else if (main.sst_exposure.trim().equals(main.THROUGH_HULL_SENSOR))
      jRadioButton14.setSelected(true);
    else if (main.sst_exposure.trim().equals(main.RADIATION_THERMOMETER))
      jRadioButton15.setSelected(true);
    else if (main.sst_exposure.trim().equals(main.BAIT_TANKS_THERMOMETER))
      jRadioButton16.setSelected(true);

    // wind units in graps/dasboard
    // NB For the tiem being always knots!!!!!
    // jRadioButton18.setSelected(true);
  }

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    java.awt.EventQueue.invokeLater(
        new Runnable() {
          @Override
          public void run() {
            new mystationdata().setVisible(true);
          }
        });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.ButtonGroup buttonGroup1;
  private javax.swing.ButtonGroup buttonGroup2;
  private javax.swing.ButtonGroup buttonGroup3;
  private javax.swing.ButtonGroup buttonGroup4;
  private javax.swing.ButtonGroup buttonGroup5;
  private javax.swing.ButtonGroup buttonGroup6;
  private javax.swing.JButton jButton1;
  private javax.swing.JButton jButton2;
  private javax.swing.JButton jButton3;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel10;
  private javax.swing.JLabel jLabel11;
  private javax.swing.JLabel jLabel12;
  private javax.swing.JLabel jLabel13;
  private javax.swing.JLabel jLabel14;
  private javax.swing.JLabel jLabel15;
  private javax.swing.JLabel jLabel16;
  private javax.swing.JLabel jLabel17;
  private javax.swing.JLabel jLabel18;
  private javax.swing.JLabel jLabel19;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel20;
  private javax.swing.JLabel jLabel21;
  private javax.swing.JLabel jLabel22;
  private javax.swing.JLabel jLabel23;
  private javax.swing.JLabel jLabel24;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JLabel jLabel8;
  private javax.swing.JLabel jLabel9;
  private javax.swing.JList<String> jList2;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JPanel jPanel3;
  private javax.swing.JPanel jPanel4;
  private javax.swing.JPanel jPanel6;
  private javax.swing.JRadioButton jRadioButton1;
  private javax.swing.JRadioButton jRadioButton10;
  private javax.swing.JRadioButton jRadioButton11;
  private javax.swing.JRadioButton jRadioButton12;
  private javax.swing.JRadioButton jRadioButton13;
  private javax.swing.JRadioButton jRadioButton14;
  private javax.swing.JRadioButton jRadioButton15;
  private javax.swing.JRadioButton jRadioButton16;
  private javax.swing.JRadioButton jRadioButton17;
  private javax.swing.JRadioButton jRadioButton18;
  private javax.swing.JRadioButton jRadioButton19;
  private javax.swing.JRadioButton jRadioButton2;
  private javax.swing.JRadioButton jRadioButton3;
  private javax.swing.JRadioButton jRadioButton4;
  private javax.swing.JRadioButton jRadioButton5;
  private javax.swing.JRadioButton jRadioButton6;
  private javax.swing.JRadioButton jRadioButton7;
  private javax.swing.JRadioButton jRadioButton8;
  private javax.swing.JRadioButton jRadioButton9;
  private javax.swing.JScrollPane jScrollPane2;
  private javax.swing.JSeparator jSeparator1;
  private javax.swing.JTextField jTextField1;
  private javax.swing.JTextField jTextField10;
  private javax.swing.JTextField jTextField2;
  private javax.swing.JTextField jTextField3;
  private javax.swing.JTextField jTextField5;
  private javax.swing.JTextField jTextField6;
  private javax.swing.JTextField jTextField7;
  private javax.swing.JTextField jTextField8;
  private javax.swing.JTextField jTextField9;
  // End of variables declaration//GEN-END:variables

  // constants
  static final int MAX_AANTAL_ISO_LANDEN_REGELS = 300;
  // private final String STATION_HELP_DIR             = "station.html";

  // var's scope only this module
  private String[] iso_landen_regels =
      new String[MAX_AANTAL_ISO_LANDEN_REGELS]; // default values: null

  private static String import_file;
  Pattern badChar;
}
