package turbowin;

import java.awt.Color;
import java.awt.Toolkit;
import javax.swing.JTextField;

/** Initializes the main window elements that are not generated by the GUI builder. */
final class StartupWindowWorkflow {

  private StartupWindowWorkflow() {}

  static void initialize(main owner) {
    main.support_class = new main_support();

    owner.setTitle(main.APPLICATION_NAME);
    main.jLabel4.setText(main.APPLICATION_NAME);
    owner.setIconImage(
        Toolkit.getDefaultToolkit()
            .getImage(owner.getClass().getResource(main.ICONS_DIRECTORY + "tray.png")));
    configureStatusField(main.jTextField4);
  }

  static void configureStatusField(JTextField statusField) {
    statusField.setBackground(new Color(204, 255, 255));
    statusField.setName("fm13_field");
  }
}
