#!/bin/sh
# postinst script for APPLICATION_PACKAGE
#
# see: dh_installdeb(1)

set -e

# summary of how this script can be called:
#        * <postinst> `configure' <most-recently-configured-version>
#        * <old-postinst> `abort-upgrade' <new version>
#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
#          <new-version>
#        * <postinst> `abort-remove'
#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
#          <failed-install-package> <version> `removing'
#          <conflicting-package> <version>
# for details, see https://www.debian.org/doc/debian-policy/ or
# the debian-policy package

package_type=deb
LAUNCHER_AS_SERVICE_SCRIPTS

case "$1" in
    configure)
DESKTOP_COMMANDS_INSTALL
LAUNCHER_AS_SERVICE_COMMANDS_INSTALL
# Create custom data directory and set permission for shared access (777 for full access)
mkdir -p /opt/turbowinplus/data
chmod 777 /opt/turbowinplus/data
# Set umask to 000 to allow full shared access to the data directory before launching the application.
# The script creates a wrapper that sets the umask and then launches the actual TurboWinPlus binary.
mv /opt/turbowinplus/bin/TurboWinPlus /opt/turbowinplus/bin/TurboWinPlus.run
mv /opt/turbowinplus/lib/app/TurboWinPlus.cfg /opt/turbowinplus/lib/app/TurboWinPlus.run.cfg
cat <<EOF > /opt/turbowinplus/bin/TurboWinPlus
#!/bin/bash
umask 000
exec /opt/turbowinplus/bin/TurboWinPlus.run "\$@"
EOF
chmod +x /opt/turbowinplus/bin/TurboWinPlus
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
