/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package turbowin;

import java.awt.Cursor;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.List;
import javax.swing.SwingWorker;

/**
 *
 * @author martin
 */
public class mydevice_log extends javax.swing.JFrame {

   /**
    * Creates new form mydevice_log
    */
   public mydevice_log() {
      initComponents();
      initComponents2();
   }

   /**
    * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form
    * Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jScrollPane1 = new javax.swing.JScrollPane();
      jTextArea1 = new javax.swing.JTextArea();

      setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
      setTitle("turboWin+ device log");

      jTextArea1.setEditable(false);
      jTextArea1.setColumns(20);
      jTextArea1.setRows(5);
      jScrollPane1.setViewportView(jTextArea1);

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 825, Short.MAX_VALUE)
            .addContainerGap())
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 516, Short.MAX_VALUE)
            .addContainerGap())
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

   
   /***********************************************************************************************/
   /*                                                                                             */
   /*                                                                                             */
   /*                                                                                             */
   /***********************************************************************************************/
   private String connected_devices_in_plain_language()
   {
      String connected_devices = null;
      
      if (main.RS232_connection_mode == 0)
      {
         connected_devices = "none";
      } 
      if (main.RS232_connection_mode == 1)
      {
         connected_devices = "Vaisala PTB220 serial";
      }   
      if (main.RS232_connection_mode == 2)
      {
         connected_devices = "Vaisala PTB330 serial";
      }   
      if (main.RS232_connection_mode == 3)
      {
         connected_devices = "EUCAWS AWS serial";
      }   
      if (main.RS232_connection_mode == 4)
      {
         connected_devices = "Mintaka DUO USB";
      }   
      if (main.RS232_connection_mode == 5)
      {
         connected_devices = "Mintaka Star USB";
      }   
      if (main.RS232_connection_mode == 6)
      {
         connected_devices = "Mintaka Star LAN";
      }   
      if (main.RS232_connection_mode == 7)
      {
         connected_devices = "Mintaka Star serial + Mintaka StarX WiFi";
      }   
      if (main.RS232_connection_mode == 8)
      {
         connected_devices = "Mintaka Star LAN + Mintaka StarX WiFi";
      }      
      if (main.RS232_connection_mode == 9)
      {
         connected_devices = "OMC-140 AWS serial";
      }                              
      if (main.RS232_connection_mode == 10)
      {
         connected_devices = "OMC-140 AWS LAN";
      }
      if (main.RS232_connection_mode == 11)
      {
         connected_devices = "AMOS2X AWS serial";
      }    
      
      if (main.RS232_connection_mode_II == 1)
      {
         if (connected_devices == null)
         {   
            connected_devices = "Vaisala HMP155 USB";
         }
         else
         {
            connected_devices += " + Vaisala HMP155 USB";
         }
      }
      
      if (main.RS232_GPS_connection_mode == 1)
      {
         if (connected_devices == null)
         {
            connected_devices = "GPS (NMEA 0183)";
         }
         else
         {
            connected_devices += " + GPS (NMEA 0183)";
         }
      }
      
      
      return connected_devices;
   }   
   
   
   
   /***********************************************************************************************/
   /*                                                                                             */
   /*                                                                                             */
   /*                                                                                             */
   /***********************************************************************************************/
   private String log_separator()
   {
      String log_separator = "\n====================================================================================================================================\n";


      return log_separator;   
   }
   
  
   
   /***********************************************************************************************/
   /*                                                                                             */
   /*                                                                                             */
   /*                                                                                             */
   /***********************************************************************************************/
   private void initComponents2()
   {
      final String newline = System.getProperty("line.separator");
      
      
      // eg http://www.javacreed.com/swing-worker-example/
      
      setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
      setTitle("TurboWin+ device log");
      
      new SwingWorker<String, String>()
      {
         @Override
         protected String doInBackground() throws Exception
         {
            String file_line = null;
            int teller1 = 0;                                     // for counting total number of records in requested file (first loop)
            int teller2 = -1;                                    // for counting numer of records in requested file (second loop)
            boolean doorgaan = true;
            
            String connected_devices = connected_devices_in_plain_language();
            
            // write general comment in the device window log 
            publish(new String[] { "--- GENERAL ---" });
            publish(new String[] { "ship name: " + main.ship_name });
            publish(new String[] { "connected device(s) according user settings: " + connected_devices });
            publish(new String[] { "showing: raw received data records from device + per record last 12 characters added by this program indicating UTC timestamp (YYYYMMDDHHMM) storage"});
            publish(new String[] { "date/time log invoke: " + main.sdf_tsl_2.format(new Date()) + " UTC" });   //  new Date() -> always in UTC
            
            // posibilities:
            //     sensor_data_file_type_1_present e.g. sensor_data_2024032607.txt
            //     sensor_data_file_type_2_present e.g. sensor_data_II_2024032607.txt
            //
            boolean sensor_data_file_type_1_present = false;
            boolean sensor_data_file_type_2_present = false;
            if (main.RS232_connection_mode != 0)
            {
               sensor_data_file_type_1_present = true;
            }
            if (main.RS232_connection_mode_II != 0)
            {
               sensor_data_file_type_2_present = true;
            }
            
            int start = 0;
            int end = 0;
            if (sensor_data_file_type_1_present && sensor_data_file_type_2_present)
            {
               start = 1;
               end = 2;
            }
            if (sensor_data_file_type_1_present && !sensor_data_file_type_2_present)
            {
               start = 1;
               end = 1;
            }
            if (!sensor_data_file_type_1_present && sensor_data_file_type_2_present)
            {
               start = 2;
               end = 2;
            }
            
            //
            // sensor data (GPS data yes or no included)
            //
            for (int i = start; i <= end; i++)
            {   
               publish(new String[] { log_separator() });    

               // read (from the last sensor data file) and write the sensor data records on the window log
               if (i == 1)
               {
                  publish(new String[] { "--- RECEIVED DATA [CURRENT HOUR] ---" });
               }
               else if (i == 2)
               {
                  publish(new String[] { "--- RECEIVED DATA 2ND METEO INSTRUMENT [CURRENT HOUR] ---" });
               }
               
               GregorianCalendar sensor_data_file_datum_tijd = new GregorianCalendar();
               sensor_data_file_datum_tijd.add(Calendar.MINUTE, -2);     // of is -1 ook goed????? : to be sure there was all time that it was written to the file

               // determine sensor data file name
               String sensor_data_file_naam_datum_tijd_deel = main.sdf3.format(sensor_data_file_datum_tijd.getTime()); // e.g. 2013020308
               
               String sensor_data_file_name = "";
               if (i == 1)
               {
                  sensor_data_file_name = "sensor_data_" + sensor_data_file_naam_datum_tijd_deel + ".txt";
               } 
               else if (i == 2)
               {
                  sensor_data_file_name = "sensor_data_II_" + sensor_data_file_naam_datum_tijd_deel + ".txt";
               }

               // first check if there is a sensor data file present (and not empty)
               String volledig_path_sensor_data = main.logs_dir + java.io.File.separator + sensor_data_file_name;

               File sensor_data_file = new File(volledig_path_sensor_data);
               if (sensor_data_file.exists())
               {
                  doorgaan = true;
               }  
               else
               {
                  publish(new String[] { "no device data file found (" + volledig_path_sensor_data + ")"});
                  doorgaan = false;
               }

               if (doorgaan && sensor_data_file.length() == 0)          // NB length() in bytes
               {
                  publish(new String[] { "no data found, empty device file (" + volledig_path_sensor_data + ")"});
               }  

               if (doorgaan && sensor_data_file.length() > 0)     
               {
                  try (BufferedReader in = new BufferedReader(new FileReader(volledig_path_sensor_data)))
                  {
                     while ((in.readLine()) != null)   
                     {
                        teller1++;
                     }
                  } // try
                  catch (FileNotFoundException ex)
                  {
                     String info = "[GENERAL] reading error " + main.APPLICATION_NAME + " device log (sensor data) file";
                     main.log_turbowin_system_message(info);
                     doorgaan = false;
                  }
                  catch (IOException ex)
                  {
                     String info = "[GENERAL] error " + main.APPLICATION_NAME + " device log (sensor data) file (" + ex + ")";
                     main.log_turbowin_system_message(info);
                     doorgaan = false;
                  } // catch
                  System.out.println("--- device log number of records: " + teller1);


                  if (doorgaan)
                  {
                     // trick to display always the last 100 records if > 100 records stored in requested file
                     if (teller1 > 100)
                     {
                        teller2 = (teller1 -100) * -1;   // e.g. teller1 = 1700 -> teller2 = -700;
                     }
                     else
                     {
                        teller2 = -1;
                     }
                     System.out.println("--- device log displaying from record number: " + Math.abs(teller2 + 1));

                     try (BufferedReader in2 = new BufferedReader(new FileReader(volledig_path_sensor_data)))   // try with resources
                     {
                        while ((file_line = in2.readLine()) != null)
                        {
                           teller2++;
                           if (teller2 >= 0)
                           {
                              publish(new String[] { file_line });
                           }
                        } // while ((file_line = in2.readLine()) != null)
                     }
                     catch (FileNotFoundException ex)
                     {
                        String info = "[GENERAL] reading error " + main.APPLICATION_NAME + " device log (sensor data) file";
                        main.log_turbowin_system_message(info);
                        doorgaan = false;
                     }
                     catch (IOException ex)
                     {
                        String info = "[GENERAL] error " + main.APPLICATION_NAME + " device log (sensor data) file (" + ex + ")";
                        main.log_turbowin_system_message(info);
                        doorgaan = false;
                     } // catch

                  } // if (doorgaan)

               } // if (doorgaan && sensor_data_file.length() > 0)     
            } // for (int i = start; i < end; i++)
            
            return null;
         } // protected Void doInBackground() throws Exception
         
         @Override
         protected void process(List<String> data)
         {
            // process: Receives data chunks from the publish method asynchronously on the Event Dispatch Thread.
            for (String received_line: data)
            {
               // NB eg http://www.javacreed.com/swing-worker-example/
               //    This swing component is only accessed from the process() method and never used from within the doInBackbround() method 
               //    or other methods directly (by directly we mean from the same thread) invoked from it. 

               // NB altijd in for loop omdat meerdere ontvangen string's verzameld kunnen zijn voordat het hier geprocessed wordt(inherent aan SwingWorker)
               jTextArea1.append(received_line);
               jTextArea1.append(newline);
            }
         } // protected void process(List<String> data)

         @Override
         protected void done()
         {
            setCursor(Cursor.getPredefinedCursor(Cursor.	DEFAULT_CURSOR));
         } // protected void done()
         
      }.execute(); // new SwingWorker<String, String>()
      
      
      //
      // GPS data (only available in this setting if it comes from a separated device, like a mini-GPS)
      //
      if (main.RS232_GPS_connection_mode == 1)
      {
         setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));

         new SwingWorker<String, String>()
         {
            @Override
            protected String doInBackground() throws Exception
            {
               publish(new String[] { log_separator() }); 
               publish(new String[] { newline });
               publish(new String[] { "--- RECEIVED GPS DATA ---" });

               String GPS_memory_line = "";
               for (int m = main_RS232_RS422.MAX_GPS_ARRAY; m > 0; m--)
               {
                  GPS_memory_line = main_RS232_RS422.GPS_array_device_log[m];
                  publish(new String[] { GPS_memory_line });
               }         

               return null;
            } // protected Void doInBackground() throws Exception  

            @Override
            protected void process(List<String> data)
            {
               // process: Receives data chunks from the publish method asynchronously on the Event Dispatch Thread.
               for (String received_line: data)
               {
                  // NB eg http://www.javacreed.com/swing-worker-example/
                  //    This swing component is only accessed from the process() method and never used from within the doInBackbround() method 
                  //    or other methods directly (by directly we mean from the same thread) invoked from it. 

                  // NB altijd in for loop omdat meerdere ontvangen string's verzameld kunnen zijn voordat het hier geprocessed wordt(inherent aan SwingWorker)
                  jTextArea1.append(received_line);
               }
            } // protected void process(List<String> data)

            @Override
            protected void done()
            {
               setCursor(Cursor.getPredefinedCursor(Cursor.	DEFAULT_CURSOR));
            } // protected void done()         
         }.execute(); // new SwingWorker<String, String>()
      } // if (main.RS232_GPS_connection_mode == 1)
   }

   
   
   
   /**
    * @param args the command line arguments
    */
   public static void main(String args[]) {
      /* Set the Nimbus look and feel */
      //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
      /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
       */
      try {
         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
               javax.swing.UIManager.setLookAndFeel(info.getClassName());
               break;
            }
         }
      } catch (ClassNotFoundException ex) {
         java.util.logging.Logger.getLogger(mydevice_log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (InstantiationException ex) {
         java.util.logging.Logger.getLogger(mydevice_log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (IllegalAccessException ex) {
         java.util.logging.Logger.getLogger(mydevice_log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (javax.swing.UnsupportedLookAndFeelException ex) {
         java.util.logging.Logger.getLogger(mydevice_log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      //</editor-fold>

      /* Create and display the form */
      java.awt.EventQueue.invokeLater(new Runnable() {
         @Override
         public void run() {
            new mydevice_log().setVisible(true);
         }
      });
   }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JScrollPane jScrollPane1;
   private javax.swing.JTextArea jTextArea1;
   // End of variables declaration//GEN-END:variables
}
