name: exe

on:
  push:
  pull_request:

jobs:
  exe:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build EXE package
        run: powershell -File scripts/task_windows.ps1
        env:
          TURBOWIN_EMAIL_ENCRYPTION_KEY: ${{ secrets.TURBOWIN_EMAIL_ENCRYPTION_KEY }}
          TURBOWIN_EMAIL_CHARACTER_ENCODING: ${{ secrets.TURBOWIN_EMAIL_CHARACTER_ENCODING }}
          TURBOWIN_EMAIL_CIPHER_TRANSFORMATION: ${{ secrets.TURBOWIN_EMAIL_CIPHER_TRANSFORMATION }}
          TURBOWIN_EMAIL_AES_ENCRYPTION_ALGORITHM: ${{ secrets.TURBOWIN_EMAIL_AES_ENCRYPTION_ALGORITHM }}
      - name: Upload EXE artifacts
        uses: actions/upload-artifact@v4
        with:
          name: exe-artifacts
          path: build/jpackage/*
